<?php

/**
 * BigCommerceSSOApi
 * PHP version 7.4
 *
 * @category Class
 * @package  LoginRadius\Sdk\Internal\OpenApi
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * LoginRadius API
 *
 * This is a LoginRadius API server. Which you can use to authenticate and manage the user.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@loginradius.com
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.10.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace LoginRadius\Sdk\Internal\OpenApi\Api;

use GuzzleHttp\Client;
use GuzzleHttp\ClientInterface;
use GuzzleHttp\Exception\ConnectException;
use GuzzleHttp\Exception\RequestException;
use GuzzleHttp\Psr7\MultipartStream;
use GuzzleHttp\Psr7\Request;
use GuzzleHttp\RequestOptions;
use LoginRadius\Sdk\Internal\OpenApi\ApiException;
use LoginRadius\Sdk\Internal\OpenApi\Configuration;
use LoginRadius\Sdk\Internal\OpenApi\HeaderSelector;
use LoginRadius\Sdk\Internal\OpenApi\ObjectSerializer;

/**
 * BigCommerceSSOApi Class Doc Comment
 *
 * @category Class
 * @package  LoginRadius\Sdk\Internal\OpenApi
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class BigCommerceSSOApi
{
    /**
     * @var ClientInterface
     */
    protected $client;

    /**
     * @var Configuration
     */
    protected $config;

    /**
     * @var HeaderSelector
     */
    protected $headerSelector;

    /**
     * @var int Host index
     */
    protected $hostIndex;

    /** @var string[] $contentTypes **/
    public const contentTypes = [
        'bigCommerceAuth' => [
            'application/json',
        ],
        'getBigCommerceLoginUrl' => [
            'application/json',
        ],
        'postBigCommerceLoginUrl' => [
            'application/json',
        ],
        'validateBigCommercePassword' => [
            'application/json',
        ],
    ];

    /**
     * @param ClientInterface $client
     * @param Configuration   $config
     * @param HeaderSelector  $selector
     * @param int             $hostIndex (Optional) host index to select the list of hosts if defined in the OpenAPI spec
     */
    public function __construct(
        ClientInterface $client = null,
        Configuration $config = null,
        HeaderSelector $selector = null,
        $hostIndex = 0
    ) {
        $this->client = $client ?: new Client();
        $this->config = $config ?: Configuration::getDefaultConfiguration();
        $this->headerSelector = $selector ?: new HeaderSelector();
        $this->hostIndex = $hostIndex;
    }

    /**
     * Set the host index
     *
     * @param int $hostIndex Host index (required)
     */
    public function setHostIndex($hostIndex): void
    {
        $this->hostIndex = $hostIndex;
    }

    /**
     * Get the host index
     *
     * @return int Host index
     */
    public function getHostIndex()
    {
        return $this->hostIndex;
    }

    /**
     * @return Configuration
     */
    public function getConfig()
    {
        return $this->config;
    }

    /**
     * Operation bigCommerceAuth
     *
     * BigCommerce OAuth Authorization
     *
     * This operation contains host(s) defined in the OpenAPI spec. Use 'hostIndex' to select the host.
     * if needed, use the 'variables' parameter to pass variables to the host.
     * URL: https://{domain}.hub.loginradius.com
     *  Variables:
     *    - domain: LoginRadius Tenant Name
     *
     * @param  string $code BigCommerce OAuth authorization code (optional)
     * @param  string $signedPayload BigCommerce signed payload for load/uninstall callbacks (optional)
     * @param  null|int $hostIndex Host index. Defaults to null. If null, then the library will use $this->hostIndex instead
     * @param  array $variables Associative array of variables to pass to the host. Defaults to empty array.
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['bigCommerceAuth'] to see the possible values for this operation
     *
     * @throws \LoginRadius\Sdk\Internal\OpenApi\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return string|\LoginRadius\Sdk\Internal\OpenApi\Model\ErrorResponse
     */
    public function bigCommerceAuth($code = null, $signedPayload = null, ?int $hostIndex = null, array $variables = [], string $contentType = self::contentTypes['bigCommerceAuth'][0])
    {
        list($response) = $this->bigCommerceAuthWithHttpInfo($code, $signedPayload, $hostIndex, $variables, $contentType);
        return $response;
    }

    /**
     * Operation bigCommerceAuthWithHttpInfo
     *
     * BigCommerce OAuth Authorization
     *
     * This operation contains host(s) defined in the OpenAPI spec. Use 'hostIndex' to select the host.
     * if needed, use the 'variables' parameter to pass variables to the host.
     * URL: https://{domain}.hub.loginradius.com
     *  Variables:
     *    - domain: LoginRadius Tenant Name
     *
     * @param  string $code BigCommerce OAuth authorization code (optional)
     * @param  string $signedPayload BigCommerce signed payload for load/uninstall callbacks (optional)
     * @param  null|int $hostIndex Host index. Defaults to null. If null, then the library will use $this->hostIndex instead
     * @param  array $variables Associative array of variables to pass to the host. Defaults to empty array.
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['bigCommerceAuth'] to see the possible values for this operation
     *
     * @throws \LoginRadius\Sdk\Internal\OpenApi\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of string|\LoginRadius\Sdk\Internal\OpenApi\Model\ErrorResponse, HTTP status code, HTTP response headers (array of strings)
     */
    public function bigCommerceAuthWithHttpInfo($code = null, $signedPayload = null, ?int $hostIndex = null, array $variables = [], string $contentType = self::contentTypes['bigCommerceAuth'][0])
    {
        $request = $this->bigCommerceAuthRequest($code, $signedPayload, $hostIndex, $variables, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            switch ($statusCode) {
                case 200:
                    if ('string' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ('string' !== 'string') {
                            try {
                                $content = json_decode($content, false, 512, JSON_THROW_ON_ERROR);
                            } catch (\JsonException $exception) {
                                throw new ApiException(
                                    sprintf(
                                        'Error JSON decoding server response (%s)',
                                        $request->getUri()
                                    ),
                                    $statusCode,
                                    $response->getHeaders(),
                                    $content
                                );
                            }
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, 'string', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                case 400:
                    if ('\LoginRadius\Sdk\Internal\OpenApi\Model\ErrorResponse' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ('\LoginRadius\Sdk\Internal\OpenApi\Model\ErrorResponse' !== 'string') {
                            try {
                                $content = json_decode($content, false, 512, JSON_THROW_ON_ERROR);
                            } catch (\JsonException $exception) {
                                throw new ApiException(
                                    sprintf(
                                        'Error JSON decoding server response (%s)',
                                        $request->getUri()
                                    ),
                                    $statusCode,
                                    $response->getHeaders(),
                                    $content
                                );
                            }
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\LoginRadius\Sdk\Internal\OpenApi\Model\ErrorResponse', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
            }

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            $returnType = 'string';
            if ($returnType === '\SplFileObject') {
                $content = $response->getBody(); //stream goes to serializer
            } else {
                $content = (string) $response->getBody();
                if ($returnType !== 'string') {
                    try {
                        $content = json_decode($content, false, 512, JSON_THROW_ON_ERROR);
                    } catch (\JsonException $exception) {
                        throw new ApiException(
                            sprintf(
                                'Error JSON decoding server response (%s)',
                                $request->getUri()
                            ),
                            $statusCode,
                            $response->getHeaders(),
                            $content
                        );
                    }
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        'string',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 400:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\LoginRadius\Sdk\Internal\OpenApi\Model\ErrorResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation bigCommerceAuthAsync
     *
     * BigCommerce OAuth Authorization
     *
     * This operation contains host(s) defined in the OpenAPI spec. Use 'hostIndex' to select the host.
     * if needed, use the 'variables' parameter to pass variables to the host.
     * URL: https://{domain}.hub.loginradius.com
     *  Variables:
     *    - domain: LoginRadius Tenant Name
     *
     * @param  string $code BigCommerce OAuth authorization code (optional)
     * @param  string $signedPayload BigCommerce signed payload for load/uninstall callbacks (optional)
     * @param  null|int $hostIndex Host index. Defaults to null. If null, then the library will use $this->hostIndex instead
     * @param  array $variables Associative array of variables to pass to the host. Defaults to empty array.
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['bigCommerceAuth'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function bigCommerceAuthAsync($code = null, $signedPayload = null, ?int $hostIndex = null, array $variables = [], string $contentType = self::contentTypes['bigCommerceAuth'][0])
    {
        return $this->bigCommerceAuthAsyncWithHttpInfo($code, $signedPayload, $hostIndex, $variables, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation bigCommerceAuthAsyncWithHttpInfo
     *
     * BigCommerce OAuth Authorization
     *
     * This operation contains host(s) defined in the OpenAPI spec. Use 'hostIndex' to select the host.
     * if needed, use the 'variables' parameter to pass variables to the host.
     * URL: https://{domain}.hub.loginradius.com
     *  Variables:
     *    - domain: LoginRadius Tenant Name
     *
     * @param  string $code BigCommerce OAuth authorization code (optional)
     * @param  string $signedPayload BigCommerce signed payload for load/uninstall callbacks (optional)
     * @param  null|int $hostIndex Host index. Defaults to null. If null, then the library will use $this->hostIndex instead
     * @param  array $variables Associative array of variables to pass to the host. Defaults to empty array.
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['bigCommerceAuth'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function bigCommerceAuthAsyncWithHttpInfo($code = null, $signedPayload = null, ?int $hostIndex = null, array $variables = [], string $contentType = self::contentTypes['bigCommerceAuth'][0])
    {
        $returnType = 'string';
        $request = $this->bigCommerceAuthRequest($code, $signedPayload, $hostIndex, $variables, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'bigCommerceAuth'
     *
    * This operation contains host(s) defined in the OpenAPI spec. Use 'hostIndex' to select the host.
    * if needed, use the 'variables' parameter to pass variables to the host.
     * URL: https://{domain}.hub.loginradius.com
     *  Variables:
    *    - domain: LoginRadius Tenant Name
     *
     * @param  string $code BigCommerce OAuth authorization code (optional)
     * @param  string $signedPayload BigCommerce signed payload for load/uninstall callbacks (optional)
     * @param  null|int $hostIndex Host index. Defaults to null. If null, then the library will use $this->hostIndex instead
     * @param  array $variables Associative array of variables to pass to the host. Defaults to empty array.
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['bigCommerceAuth'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function bigCommerceAuthRequest($code = null, $signedPayload = null, ?int $hostIndex = null, array $variables = [], string $contentType = self::contentTypes['bigCommerceAuth'][0])
    {




        $resourcePath = '/sso/bigcommerce/auth';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $code,
            'code', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $signedPayload,
            'signed_payload', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);




        $headers = $this->headerSelector->selectHeaders(
            ['text/html', 'application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }


        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        # Preserve the original behavior of server indexing.
        if ($hostIndex === null) {
            $hostIndex = $this->hostIndex;
        }

        $hostSettings = $this->getHostSettingsForbigCommerceAuth();

        if ($hostIndex < 0 || $hostIndex >= count($hostSettings)) {
            throw new \InvalidArgumentException("Invalid index {$hostIndex} when selecting the host. Must be less than ".count($hostSettings));
        }
        $operationHost = ($this->config->getLoginRadiusBaseUrlOverride() ?? Configuration::getHostString($hostSettings, $hostIndex, array_merge($this->config->getLoginRadiusServerVariables(), $variables)));
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'GET',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Returns an array of host settings for Operation bigCommerceAuth
     *
     * @return array an array of host settings
     */
    protected function getHostSettingsForbigCommerceAuth(): array
    {
        return [
            [
                "url" => "https://{domain}.hub.loginradius.com",
                "description" => "LoginRadius Hosted Plugins Server",
                "variables" => [
                    "domain" => [
                    "description" => "LoginRadius Tenant Name",
                    "default_value" => "example",
                    ]
                ]
            ]
        ];
    }

    /**
     * Operation getBigCommerceLoginUrl
     *
     * Generate BigCommerce Login URL (GET)
     *
     * This operation contains host(s) defined in the OpenAPI spec. Use 'hostIndex' to select the host.
     * if needed, use the 'variables' parameter to pass variables to the host.
     * URL: https://{domain}.hub.loginradius.com
     *  Variables:
     *    - domain: LoginRadius Tenant Name
     *
     * @param  string $accessToken Access Token of the User (required)
     * @param  string $store BigCommerce store hash identifier (required)
     * @param  string $password User&#39;s password (optional)
     * @param  string $returnUrl URL to redirect the user to after login (optional)
     * @param  null|int $hostIndex Host index. Defaults to null. If null, then the library will use $this->hostIndex instead
     * @param  array $variables Associative array of variables to pass to the host. Defaults to empty array.
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getBigCommerceLoginUrl'] to see the possible values for this operation
     *
     * @throws \LoginRadius\Sdk\Internal\OpenApi\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \LoginRadius\Sdk\Internal\OpenApi\Model\BigCommerceLoginUrlResponse|\LoginRadius\Sdk\Internal\OpenApi\Model\ErrorResponse|\LoginRadius\Sdk\Internal\OpenApi\Model\ErrorResponse|\LoginRadius\Sdk\Internal\OpenApi\Model\ErrorResponse
     */
    public function getBigCommerceLoginUrl($accessToken, $store, $password = null, $returnUrl = null, ?int $hostIndex = null, array $variables = [], string $contentType = self::contentTypes['getBigCommerceLoginUrl'][0])
    {
        list($response) = $this->getBigCommerceLoginUrlWithHttpInfo($accessToken, $store, $password, $returnUrl, $hostIndex, $variables, $contentType);
        return $response;
    }

    /**
     * Operation getBigCommerceLoginUrlWithHttpInfo
     *
     * Generate BigCommerce Login URL (GET)
     *
     * This operation contains host(s) defined in the OpenAPI spec. Use 'hostIndex' to select the host.
     * if needed, use the 'variables' parameter to pass variables to the host.
     * URL: https://{domain}.hub.loginradius.com
     *  Variables:
     *    - domain: LoginRadius Tenant Name
     *
     * @param  string $accessToken Access Token of the User (required)
     * @param  string $store BigCommerce store hash identifier (required)
     * @param  string $password User&#39;s password (optional)
     * @param  string $returnUrl URL to redirect the user to after login (optional)
     * @param  null|int $hostIndex Host index. Defaults to null. If null, then the library will use $this->hostIndex instead
     * @param  array $variables Associative array of variables to pass to the host. Defaults to empty array.
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getBigCommerceLoginUrl'] to see the possible values for this operation
     *
     * @throws \LoginRadius\Sdk\Internal\OpenApi\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \LoginRadius\Sdk\Internal\OpenApi\Model\BigCommerceLoginUrlResponse|\LoginRadius\Sdk\Internal\OpenApi\Model\ErrorResponse|\LoginRadius\Sdk\Internal\OpenApi\Model\ErrorResponse|\LoginRadius\Sdk\Internal\OpenApi\Model\ErrorResponse, HTTP status code, HTTP response headers (array of strings)
     */
    public function getBigCommerceLoginUrlWithHttpInfo($accessToken, $store, $password = null, $returnUrl = null, ?int $hostIndex = null, array $variables = [], string $contentType = self::contentTypes['getBigCommerceLoginUrl'][0])
    {
        $request = $this->getBigCommerceLoginUrlRequest($accessToken, $store, $password, $returnUrl, $hostIndex, $variables, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            switch ($statusCode) {
                case 200:
                    if ('\LoginRadius\Sdk\Internal\OpenApi\Model\BigCommerceLoginUrlResponse' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ('\LoginRadius\Sdk\Internal\OpenApi\Model\BigCommerceLoginUrlResponse' !== 'string') {
                            try {
                                $content = json_decode($content, false, 512, JSON_THROW_ON_ERROR);
                            } catch (\JsonException $exception) {
                                throw new ApiException(
                                    sprintf(
                                        'Error JSON decoding server response (%s)',
                                        $request->getUri()
                                    ),
                                    $statusCode,
                                    $response->getHeaders(),
                                    $content
                                );
                            }
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\LoginRadius\Sdk\Internal\OpenApi\Model\BigCommerceLoginUrlResponse', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                case 400:
                    if ('\LoginRadius\Sdk\Internal\OpenApi\Model\ErrorResponse' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ('\LoginRadius\Sdk\Internal\OpenApi\Model\ErrorResponse' !== 'string') {
                            try {
                                $content = json_decode($content, false, 512, JSON_THROW_ON_ERROR);
                            } catch (\JsonException $exception) {
                                throw new ApiException(
                                    sprintf(
                                        'Error JSON decoding server response (%s)',
                                        $request->getUri()
                                    ),
                                    $statusCode,
                                    $response->getHeaders(),
                                    $content
                                );
                            }
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\LoginRadius\Sdk\Internal\OpenApi\Model\ErrorResponse', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                case 401:
                    if ('\LoginRadius\Sdk\Internal\OpenApi\Model\ErrorResponse' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ('\LoginRadius\Sdk\Internal\OpenApi\Model\ErrorResponse' !== 'string') {
                            try {
                                $content = json_decode($content, false, 512, JSON_THROW_ON_ERROR);
                            } catch (\JsonException $exception) {
                                throw new ApiException(
                                    sprintf(
                                        'Error JSON decoding server response (%s)',
                                        $request->getUri()
                                    ),
                                    $statusCode,
                                    $response->getHeaders(),
                                    $content
                                );
                            }
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\LoginRadius\Sdk\Internal\OpenApi\Model\ErrorResponse', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                case 403:
                    if ('\LoginRadius\Sdk\Internal\OpenApi\Model\ErrorResponse' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ('\LoginRadius\Sdk\Internal\OpenApi\Model\ErrorResponse' !== 'string') {
                            try {
                                $content = json_decode($content, false, 512, JSON_THROW_ON_ERROR);
                            } catch (\JsonException $exception) {
                                throw new ApiException(
                                    sprintf(
                                        'Error JSON decoding server response (%s)',
                                        $request->getUri()
                                    ),
                                    $statusCode,
                                    $response->getHeaders(),
                                    $content
                                );
                            }
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\LoginRadius\Sdk\Internal\OpenApi\Model\ErrorResponse', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
            }

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            $returnType = '\LoginRadius\Sdk\Internal\OpenApi\Model\BigCommerceLoginUrlResponse';
            if ($returnType === '\SplFileObject') {
                $content = $response->getBody(); //stream goes to serializer
            } else {
                $content = (string) $response->getBody();
                if ($returnType !== 'string') {
                    try {
                        $content = json_decode($content, false, 512, JSON_THROW_ON_ERROR);
                    } catch (\JsonException $exception) {
                        throw new ApiException(
                            sprintf(
                                'Error JSON decoding server response (%s)',
                                $request->getUri()
                            ),
                            $statusCode,
                            $response->getHeaders(),
                            $content
                        );
                    }
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\LoginRadius\Sdk\Internal\OpenApi\Model\BigCommerceLoginUrlResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 400:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\LoginRadius\Sdk\Internal\OpenApi\Model\ErrorResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 401:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\LoginRadius\Sdk\Internal\OpenApi\Model\ErrorResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 403:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\LoginRadius\Sdk\Internal\OpenApi\Model\ErrorResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation getBigCommerceLoginUrlAsync
     *
     * Generate BigCommerce Login URL (GET)
     *
     * This operation contains host(s) defined in the OpenAPI spec. Use 'hostIndex' to select the host.
     * if needed, use the 'variables' parameter to pass variables to the host.
     * URL: https://{domain}.hub.loginradius.com
     *  Variables:
     *    - domain: LoginRadius Tenant Name
     *
     * @param  string $accessToken Access Token of the User (required)
     * @param  string $store BigCommerce store hash identifier (required)
     * @param  string $password User&#39;s password (optional)
     * @param  string $returnUrl URL to redirect the user to after login (optional)
     * @param  null|int $hostIndex Host index. Defaults to null. If null, then the library will use $this->hostIndex instead
     * @param  array $variables Associative array of variables to pass to the host. Defaults to empty array.
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getBigCommerceLoginUrl'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getBigCommerceLoginUrlAsync($accessToken, $store, $password = null, $returnUrl = null, ?int $hostIndex = null, array $variables = [], string $contentType = self::contentTypes['getBigCommerceLoginUrl'][0])
    {
        return $this->getBigCommerceLoginUrlAsyncWithHttpInfo($accessToken, $store, $password, $returnUrl, $hostIndex, $variables, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation getBigCommerceLoginUrlAsyncWithHttpInfo
     *
     * Generate BigCommerce Login URL (GET)
     *
     * This operation contains host(s) defined in the OpenAPI spec. Use 'hostIndex' to select the host.
     * if needed, use the 'variables' parameter to pass variables to the host.
     * URL: https://{domain}.hub.loginradius.com
     *  Variables:
     *    - domain: LoginRadius Tenant Name
     *
     * @param  string $accessToken Access Token of the User (required)
     * @param  string $store BigCommerce store hash identifier (required)
     * @param  string $password User&#39;s password (optional)
     * @param  string $returnUrl URL to redirect the user to after login (optional)
     * @param  null|int $hostIndex Host index. Defaults to null. If null, then the library will use $this->hostIndex instead
     * @param  array $variables Associative array of variables to pass to the host. Defaults to empty array.
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getBigCommerceLoginUrl'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getBigCommerceLoginUrlAsyncWithHttpInfo($accessToken, $store, $password = null, $returnUrl = null, ?int $hostIndex = null, array $variables = [], string $contentType = self::contentTypes['getBigCommerceLoginUrl'][0])
    {
        $returnType = '\LoginRadius\Sdk\Internal\OpenApi\Model\BigCommerceLoginUrlResponse';
        $request = $this->getBigCommerceLoginUrlRequest($accessToken, $store, $password, $returnUrl, $hostIndex, $variables, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'getBigCommerceLoginUrl'
     *
    * This operation contains host(s) defined in the OpenAPI spec. Use 'hostIndex' to select the host.
    * if needed, use the 'variables' parameter to pass variables to the host.
     * URL: https://{domain}.hub.loginradius.com
     *  Variables:
    *    - domain: LoginRadius Tenant Name
     *
     * @param  string $accessToken Access Token of the User (required)
     * @param  string $store BigCommerce store hash identifier (required)
     * @param  string $password User&#39;s password (optional)
     * @param  string $returnUrl URL to redirect the user to after login (optional)
     * @param  null|int $hostIndex Host index. Defaults to null. If null, then the library will use $this->hostIndex instead
     * @param  array $variables Associative array of variables to pass to the host. Defaults to empty array.
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getBigCommerceLoginUrl'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function getBigCommerceLoginUrlRequest($accessToken, $store, $password = null, $returnUrl = null, ?int $hostIndex = null, array $variables = [], string $contentType = self::contentTypes['getBigCommerceLoginUrl'][0])
    {

        // verify the required parameter 'accessToken' is set
        if ($accessToken === null || (is_array($accessToken) && count($accessToken) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $accessToken when calling getBigCommerceLoginUrl'
            );
        }

        // verify the required parameter 'store' is set
        if ($store === null || (is_array($store) && count($store) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $store when calling getBigCommerceLoginUrl'
            );
        }




        $resourcePath = '/sso/bigcommerce/api/token';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $accessToken,
            'access_token', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            true // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $store,
            'store', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            true // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $password,
            'password', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $returnUrl,
            'return_url', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);




        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('apikey');
        if ($apiKey !== null) {
            $queryParams['apikey'] = $apiKey;
        }
        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('X-LoginRadius-ApiKey');
        if ($apiKey !== null) {
            $headers['X-LoginRadius-ApiKey'] = $apiKey;
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        # Preserve the original behavior of server indexing.
        if ($hostIndex === null) {
            $hostIndex = $this->hostIndex;
        }

        $hostSettings = $this->getHostSettingsForgetBigCommerceLoginUrl();

        if ($hostIndex < 0 || $hostIndex >= count($hostSettings)) {
            throw new \InvalidArgumentException("Invalid index {$hostIndex} when selecting the host. Must be less than ".count($hostSettings));
        }
        $operationHost = ($this->config->getLoginRadiusBaseUrlOverride() ?? Configuration::getHostString($hostSettings, $hostIndex, array_merge($this->config->getLoginRadiusServerVariables(), $variables)));
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'GET',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Returns an array of host settings for Operation getBigCommerceLoginUrl
     *
     * @return array an array of host settings
     */
    protected function getHostSettingsForgetBigCommerceLoginUrl(): array
    {
        return [
            [
                "url" => "https://{domain}.hub.loginradius.com",
                "description" => "LoginRadius Hosted Plugins Server",
                "variables" => [
                    "domain" => [
                    "description" => "LoginRadius Tenant Name",
                    "default_value" => "example",
                    ]
                ]
            ]
        ];
    }

    /**
     * Operation postBigCommerceLoginUrl
     *
     * Generate BigCommerce Login URL (POST)
     *
     * This operation contains host(s) defined in the OpenAPI spec. Use 'hostIndex' to select the host.
     * if needed, use the 'variables' parameter to pass variables to the host.
     * URL: https://{domain}.hub.loginradius.com
     *  Variables:
     *    - domain: LoginRadius Tenant Name
     *
     * @param  string $store BigCommerce store hash identifier (required)
     * @param  \LoginRadius\Sdk\Internal\OpenApi\Model\BigCommerceTokenPostRequest $bigCommerceTokenPostRequest bigCommerceTokenPostRequest (required)
     * @param  null|int $hostIndex Host index. Defaults to null. If null, then the library will use $this->hostIndex instead
     * @param  array $variables Associative array of variables to pass to the host. Defaults to empty array.
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['postBigCommerceLoginUrl'] to see the possible values for this operation
     *
     * @throws \LoginRadius\Sdk\Internal\OpenApi\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \LoginRadius\Sdk\Internal\OpenApi\Model\BigCommerceLoginUrlResponse|\LoginRadius\Sdk\Internal\OpenApi\Model\ErrorResponse|\LoginRadius\Sdk\Internal\OpenApi\Model\ErrorResponse|\LoginRadius\Sdk\Internal\OpenApi\Model\ErrorResponse
     */
    public function postBigCommerceLoginUrl($store, $bigCommerceTokenPostRequest, ?int $hostIndex = null, array $variables = [], string $contentType = self::contentTypes['postBigCommerceLoginUrl'][0])
    {
        list($response) = $this->postBigCommerceLoginUrlWithHttpInfo($store, $bigCommerceTokenPostRequest, $hostIndex, $variables, $contentType);
        return $response;
    }

    /**
     * Operation postBigCommerceLoginUrlWithHttpInfo
     *
     * Generate BigCommerce Login URL (POST)
     *
     * This operation contains host(s) defined in the OpenAPI spec. Use 'hostIndex' to select the host.
     * if needed, use the 'variables' parameter to pass variables to the host.
     * URL: https://{domain}.hub.loginradius.com
     *  Variables:
     *    - domain: LoginRadius Tenant Name
     *
     * @param  string $store BigCommerce store hash identifier (required)
     * @param  \LoginRadius\Sdk\Internal\OpenApi\Model\BigCommerceTokenPostRequest $bigCommerceTokenPostRequest (required)
     * @param  null|int $hostIndex Host index. Defaults to null. If null, then the library will use $this->hostIndex instead
     * @param  array $variables Associative array of variables to pass to the host. Defaults to empty array.
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['postBigCommerceLoginUrl'] to see the possible values for this operation
     *
     * @throws \LoginRadius\Sdk\Internal\OpenApi\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \LoginRadius\Sdk\Internal\OpenApi\Model\BigCommerceLoginUrlResponse|\LoginRadius\Sdk\Internal\OpenApi\Model\ErrorResponse|\LoginRadius\Sdk\Internal\OpenApi\Model\ErrorResponse|\LoginRadius\Sdk\Internal\OpenApi\Model\ErrorResponse, HTTP status code, HTTP response headers (array of strings)
     */
    public function postBigCommerceLoginUrlWithHttpInfo($store, $bigCommerceTokenPostRequest, ?int $hostIndex = null, array $variables = [], string $contentType = self::contentTypes['postBigCommerceLoginUrl'][0])
    {
        $request = $this->postBigCommerceLoginUrlRequest($store, $bigCommerceTokenPostRequest, $hostIndex, $variables, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            switch ($statusCode) {
                case 200:
                    if ('\LoginRadius\Sdk\Internal\OpenApi\Model\BigCommerceLoginUrlResponse' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ('\LoginRadius\Sdk\Internal\OpenApi\Model\BigCommerceLoginUrlResponse' !== 'string') {
                            try {
                                $content = json_decode($content, false, 512, JSON_THROW_ON_ERROR);
                            } catch (\JsonException $exception) {
                                throw new ApiException(
                                    sprintf(
                                        'Error JSON decoding server response (%s)',
                                        $request->getUri()
                                    ),
                                    $statusCode,
                                    $response->getHeaders(),
                                    $content
                                );
                            }
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\LoginRadius\Sdk\Internal\OpenApi\Model\BigCommerceLoginUrlResponse', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                case 400:
                    if ('\LoginRadius\Sdk\Internal\OpenApi\Model\ErrorResponse' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ('\LoginRadius\Sdk\Internal\OpenApi\Model\ErrorResponse' !== 'string') {
                            try {
                                $content = json_decode($content, false, 512, JSON_THROW_ON_ERROR);
                            } catch (\JsonException $exception) {
                                throw new ApiException(
                                    sprintf(
                                        'Error JSON decoding server response (%s)',
                                        $request->getUri()
                                    ),
                                    $statusCode,
                                    $response->getHeaders(),
                                    $content
                                );
                            }
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\LoginRadius\Sdk\Internal\OpenApi\Model\ErrorResponse', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                case 401:
                    if ('\LoginRadius\Sdk\Internal\OpenApi\Model\ErrorResponse' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ('\LoginRadius\Sdk\Internal\OpenApi\Model\ErrorResponse' !== 'string') {
                            try {
                                $content = json_decode($content, false, 512, JSON_THROW_ON_ERROR);
                            } catch (\JsonException $exception) {
                                throw new ApiException(
                                    sprintf(
                                        'Error JSON decoding server response (%s)',
                                        $request->getUri()
                                    ),
                                    $statusCode,
                                    $response->getHeaders(),
                                    $content
                                );
                            }
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\LoginRadius\Sdk\Internal\OpenApi\Model\ErrorResponse', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                case 403:
                    if ('\LoginRadius\Sdk\Internal\OpenApi\Model\ErrorResponse' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ('\LoginRadius\Sdk\Internal\OpenApi\Model\ErrorResponse' !== 'string') {
                            try {
                                $content = json_decode($content, false, 512, JSON_THROW_ON_ERROR);
                            } catch (\JsonException $exception) {
                                throw new ApiException(
                                    sprintf(
                                        'Error JSON decoding server response (%s)',
                                        $request->getUri()
                                    ),
                                    $statusCode,
                                    $response->getHeaders(),
                                    $content
                                );
                            }
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\LoginRadius\Sdk\Internal\OpenApi\Model\ErrorResponse', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
            }

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            $returnType = '\LoginRadius\Sdk\Internal\OpenApi\Model\BigCommerceLoginUrlResponse';
            if ($returnType === '\SplFileObject') {
                $content = $response->getBody(); //stream goes to serializer
            } else {
                $content = (string) $response->getBody();
                if ($returnType !== 'string') {
                    try {
                        $content = json_decode($content, false, 512, JSON_THROW_ON_ERROR);
                    } catch (\JsonException $exception) {
                        throw new ApiException(
                            sprintf(
                                'Error JSON decoding server response (%s)',
                                $request->getUri()
                            ),
                            $statusCode,
                            $response->getHeaders(),
                            $content
                        );
                    }
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\LoginRadius\Sdk\Internal\OpenApi\Model\BigCommerceLoginUrlResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 400:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\LoginRadius\Sdk\Internal\OpenApi\Model\ErrorResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 401:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\LoginRadius\Sdk\Internal\OpenApi\Model\ErrorResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 403:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\LoginRadius\Sdk\Internal\OpenApi\Model\ErrorResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation postBigCommerceLoginUrlAsync
     *
     * Generate BigCommerce Login URL (POST)
     *
     * This operation contains host(s) defined in the OpenAPI spec. Use 'hostIndex' to select the host.
     * if needed, use the 'variables' parameter to pass variables to the host.
     * URL: https://{domain}.hub.loginradius.com
     *  Variables:
     *    - domain: LoginRadius Tenant Name
     *
     * @param  string $store BigCommerce store hash identifier (required)
     * @param  \LoginRadius\Sdk\Internal\OpenApi\Model\BigCommerceTokenPostRequest $bigCommerceTokenPostRequest (required)
     * @param  null|int $hostIndex Host index. Defaults to null. If null, then the library will use $this->hostIndex instead
     * @param  array $variables Associative array of variables to pass to the host. Defaults to empty array.
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['postBigCommerceLoginUrl'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function postBigCommerceLoginUrlAsync($store, $bigCommerceTokenPostRequest, ?int $hostIndex = null, array $variables = [], string $contentType = self::contentTypes['postBigCommerceLoginUrl'][0])
    {
        return $this->postBigCommerceLoginUrlAsyncWithHttpInfo($store, $bigCommerceTokenPostRequest, $hostIndex, $variables, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation postBigCommerceLoginUrlAsyncWithHttpInfo
     *
     * Generate BigCommerce Login URL (POST)
     *
     * This operation contains host(s) defined in the OpenAPI spec. Use 'hostIndex' to select the host.
     * if needed, use the 'variables' parameter to pass variables to the host.
     * URL: https://{domain}.hub.loginradius.com
     *  Variables:
     *    - domain: LoginRadius Tenant Name
     *
     * @param  string $store BigCommerce store hash identifier (required)
     * @param  \LoginRadius\Sdk\Internal\OpenApi\Model\BigCommerceTokenPostRequest $bigCommerceTokenPostRequest (required)
     * @param  null|int $hostIndex Host index. Defaults to null. If null, then the library will use $this->hostIndex instead
     * @param  array $variables Associative array of variables to pass to the host. Defaults to empty array.
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['postBigCommerceLoginUrl'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function postBigCommerceLoginUrlAsyncWithHttpInfo($store, $bigCommerceTokenPostRequest, ?int $hostIndex = null, array $variables = [], string $contentType = self::contentTypes['postBigCommerceLoginUrl'][0])
    {
        $returnType = '\LoginRadius\Sdk\Internal\OpenApi\Model\BigCommerceLoginUrlResponse';
        $request = $this->postBigCommerceLoginUrlRequest($store, $bigCommerceTokenPostRequest, $hostIndex, $variables, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'postBigCommerceLoginUrl'
     *
    * This operation contains host(s) defined in the OpenAPI spec. Use 'hostIndex' to select the host.
    * if needed, use the 'variables' parameter to pass variables to the host.
     * URL: https://{domain}.hub.loginradius.com
     *  Variables:
    *    - domain: LoginRadius Tenant Name
     *
     * @param  string $store BigCommerce store hash identifier (required)
     * @param  \LoginRadius\Sdk\Internal\OpenApi\Model\BigCommerceTokenPostRequest $bigCommerceTokenPostRequest (required)
     * @param  null|int $hostIndex Host index. Defaults to null. If null, then the library will use $this->hostIndex instead
     * @param  array $variables Associative array of variables to pass to the host. Defaults to empty array.
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['postBigCommerceLoginUrl'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function postBigCommerceLoginUrlRequest($store, $bigCommerceTokenPostRequest, ?int $hostIndex = null, array $variables = [], string $contentType = self::contentTypes['postBigCommerceLoginUrl'][0])
    {

        // verify the required parameter 'store' is set
        if ($store === null || (is_array($store) && count($store) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $store when calling postBigCommerceLoginUrl'
            );
        }

        // verify the required parameter 'bigCommerceTokenPostRequest' is set
        if ($bigCommerceTokenPostRequest === null || (is_array($bigCommerceTokenPostRequest) && count($bigCommerceTokenPostRequest) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $bigCommerceTokenPostRequest when calling postBigCommerceLoginUrl'
            );
        }


        $resourcePath = '/sso/bigcommerce/api/token';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $store,
            'store', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            true // required
        ) ?? []);




        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (isset($bigCommerceTokenPostRequest)) {
            if (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the body
                $httpBody = \GuzzleHttp\Utils::jsonEncode(ObjectSerializer::sanitizeForSerialization($bigCommerceTokenPostRequest));
            } else {
                $httpBody = $bigCommerceTokenPostRequest;
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('apikey');
        if ($apiKey !== null) {
            $queryParams['apikey'] = $apiKey;
        }
        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('X-LoginRadius-ApiKey');
        if ($apiKey !== null) {
            $headers['X-LoginRadius-ApiKey'] = $apiKey;
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        # Preserve the original behavior of server indexing.
        if ($hostIndex === null) {
            $hostIndex = $this->hostIndex;
        }

        $hostSettings = $this->getHostSettingsForpostBigCommerceLoginUrl();

        if ($hostIndex < 0 || $hostIndex >= count($hostSettings)) {
            throw new \InvalidArgumentException("Invalid index {$hostIndex} when selecting the host. Must be less than ".count($hostSettings));
        }
        $operationHost = ($this->config->getLoginRadiusBaseUrlOverride() ?? Configuration::getHostString($hostSettings, $hostIndex, array_merge($this->config->getLoginRadiusServerVariables(), $variables)));
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'POST',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Returns an array of host settings for Operation postBigCommerceLoginUrl
     *
     * @return array an array of host settings
     */
    protected function getHostSettingsForpostBigCommerceLoginUrl(): array
    {
        return [
            [
                "url" => "https://{domain}.hub.loginradius.com",
                "description" => "LoginRadius Hosted Plugins Server",
                "variables" => [
                    "domain" => [
                    "description" => "LoginRadius Tenant Name",
                    "default_value" => "example",
                    ]
                ]
            ]
        ];
    }

    /**
     * Operation validateBigCommercePassword
     *
     * Validate BigCommerce Customer Password
     *
     * This operation contains host(s) defined in the OpenAPI spec. Use 'hostIndex' to select the host.
     * if needed, use the 'variables' parameter to pass variables to the host.
     * URL: https://{domain}.hub.loginradius.com
     *  Variables:
     *    - domain: LoginRadius Tenant Name
     *
     * @param  string $store BigCommerce store hash identifier (required)
     * @param  \LoginRadius\Sdk\Internal\OpenApi\Model\BigCommerceValidatePasswordRequest $bigCommerceValidatePasswordRequest bigCommerceValidatePasswordRequest (required)
     * @param  null|int $hostIndex Host index. Defaults to null. If null, then the library will use $this->hostIndex instead
     * @param  array $variables Associative array of variables to pass to the host. Defaults to empty array.
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['validateBigCommercePassword'] to see the possible values for this operation
     *
     * @throws \LoginRadius\Sdk\Internal\OpenApi\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \LoginRadius\Sdk\Internal\OpenApi\Model\BigCommerceValidatePasswordResponse|\LoginRadius\Sdk\Internal\OpenApi\Model\ErrorResponse|\LoginRadius\Sdk\Internal\OpenApi\Model\ErrorResponse|\LoginRadius\Sdk\Internal\OpenApi\Model\ErrorResponse
     */
    public function validateBigCommercePassword($store, $bigCommerceValidatePasswordRequest, ?int $hostIndex = null, array $variables = [], string $contentType = self::contentTypes['validateBigCommercePassword'][0])
    {
        list($response) = $this->validateBigCommercePasswordWithHttpInfo($store, $bigCommerceValidatePasswordRequest, $hostIndex, $variables, $contentType);
        return $response;
    }

    /**
     * Operation validateBigCommercePasswordWithHttpInfo
     *
     * Validate BigCommerce Customer Password
     *
     * This operation contains host(s) defined in the OpenAPI spec. Use 'hostIndex' to select the host.
     * if needed, use the 'variables' parameter to pass variables to the host.
     * URL: https://{domain}.hub.loginradius.com
     *  Variables:
     *    - domain: LoginRadius Tenant Name
     *
     * @param  string $store BigCommerce store hash identifier (required)
     * @param  \LoginRadius\Sdk\Internal\OpenApi\Model\BigCommerceValidatePasswordRequest $bigCommerceValidatePasswordRequest (required)
     * @param  null|int $hostIndex Host index. Defaults to null. If null, then the library will use $this->hostIndex instead
     * @param  array $variables Associative array of variables to pass to the host. Defaults to empty array.
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['validateBigCommercePassword'] to see the possible values for this operation
     *
     * @throws \LoginRadius\Sdk\Internal\OpenApi\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \LoginRadius\Sdk\Internal\OpenApi\Model\BigCommerceValidatePasswordResponse|\LoginRadius\Sdk\Internal\OpenApi\Model\ErrorResponse|\LoginRadius\Sdk\Internal\OpenApi\Model\ErrorResponse|\LoginRadius\Sdk\Internal\OpenApi\Model\ErrorResponse, HTTP status code, HTTP response headers (array of strings)
     */
    public function validateBigCommercePasswordWithHttpInfo($store, $bigCommerceValidatePasswordRequest, ?int $hostIndex = null, array $variables = [], string $contentType = self::contentTypes['validateBigCommercePassword'][0])
    {
        $request = $this->validateBigCommercePasswordRequest($store, $bigCommerceValidatePasswordRequest, $hostIndex, $variables, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            switch ($statusCode) {
                case 200:
                    if ('\LoginRadius\Sdk\Internal\OpenApi\Model\BigCommerceValidatePasswordResponse' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ('\LoginRadius\Sdk\Internal\OpenApi\Model\BigCommerceValidatePasswordResponse' !== 'string') {
                            try {
                                $content = json_decode($content, false, 512, JSON_THROW_ON_ERROR);
                            } catch (\JsonException $exception) {
                                throw new ApiException(
                                    sprintf(
                                        'Error JSON decoding server response (%s)',
                                        $request->getUri()
                                    ),
                                    $statusCode,
                                    $response->getHeaders(),
                                    $content
                                );
                            }
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\LoginRadius\Sdk\Internal\OpenApi\Model\BigCommerceValidatePasswordResponse', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                case 400:
                    if ('\LoginRadius\Sdk\Internal\OpenApi\Model\ErrorResponse' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ('\LoginRadius\Sdk\Internal\OpenApi\Model\ErrorResponse' !== 'string') {
                            try {
                                $content = json_decode($content, false, 512, JSON_THROW_ON_ERROR);
                            } catch (\JsonException $exception) {
                                throw new ApiException(
                                    sprintf(
                                        'Error JSON decoding server response (%s)',
                                        $request->getUri()
                                    ),
                                    $statusCode,
                                    $response->getHeaders(),
                                    $content
                                );
                            }
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\LoginRadius\Sdk\Internal\OpenApi\Model\ErrorResponse', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                case 401:
                    if ('\LoginRadius\Sdk\Internal\OpenApi\Model\ErrorResponse' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ('\LoginRadius\Sdk\Internal\OpenApi\Model\ErrorResponse' !== 'string') {
                            try {
                                $content = json_decode($content, false, 512, JSON_THROW_ON_ERROR);
                            } catch (\JsonException $exception) {
                                throw new ApiException(
                                    sprintf(
                                        'Error JSON decoding server response (%s)',
                                        $request->getUri()
                                    ),
                                    $statusCode,
                                    $response->getHeaders(),
                                    $content
                                );
                            }
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\LoginRadius\Sdk\Internal\OpenApi\Model\ErrorResponse', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                case 403:
                    if ('\LoginRadius\Sdk\Internal\OpenApi\Model\ErrorResponse' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ('\LoginRadius\Sdk\Internal\OpenApi\Model\ErrorResponse' !== 'string') {
                            try {
                                $content = json_decode($content, false, 512, JSON_THROW_ON_ERROR);
                            } catch (\JsonException $exception) {
                                throw new ApiException(
                                    sprintf(
                                        'Error JSON decoding server response (%s)',
                                        $request->getUri()
                                    ),
                                    $statusCode,
                                    $response->getHeaders(),
                                    $content
                                );
                            }
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\LoginRadius\Sdk\Internal\OpenApi\Model\ErrorResponse', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
            }

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            $returnType = '\LoginRadius\Sdk\Internal\OpenApi\Model\BigCommerceValidatePasswordResponse';
            if ($returnType === '\SplFileObject') {
                $content = $response->getBody(); //stream goes to serializer
            } else {
                $content = (string) $response->getBody();
                if ($returnType !== 'string') {
                    try {
                        $content = json_decode($content, false, 512, JSON_THROW_ON_ERROR);
                    } catch (\JsonException $exception) {
                        throw new ApiException(
                            sprintf(
                                'Error JSON decoding server response (%s)',
                                $request->getUri()
                            ),
                            $statusCode,
                            $response->getHeaders(),
                            $content
                        );
                    }
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\LoginRadius\Sdk\Internal\OpenApi\Model\BigCommerceValidatePasswordResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 400:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\LoginRadius\Sdk\Internal\OpenApi\Model\ErrorResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 401:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\LoginRadius\Sdk\Internal\OpenApi\Model\ErrorResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 403:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\LoginRadius\Sdk\Internal\OpenApi\Model\ErrorResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation validateBigCommercePasswordAsync
     *
     * Validate BigCommerce Customer Password
     *
     * This operation contains host(s) defined in the OpenAPI spec. Use 'hostIndex' to select the host.
     * if needed, use the 'variables' parameter to pass variables to the host.
     * URL: https://{domain}.hub.loginradius.com
     *  Variables:
     *    - domain: LoginRadius Tenant Name
     *
     * @param  string $store BigCommerce store hash identifier (required)
     * @param  \LoginRadius\Sdk\Internal\OpenApi\Model\BigCommerceValidatePasswordRequest $bigCommerceValidatePasswordRequest (required)
     * @param  null|int $hostIndex Host index. Defaults to null. If null, then the library will use $this->hostIndex instead
     * @param  array $variables Associative array of variables to pass to the host. Defaults to empty array.
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['validateBigCommercePassword'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function validateBigCommercePasswordAsync($store, $bigCommerceValidatePasswordRequest, ?int $hostIndex = null, array $variables = [], string $contentType = self::contentTypes['validateBigCommercePassword'][0])
    {
        return $this->validateBigCommercePasswordAsyncWithHttpInfo($store, $bigCommerceValidatePasswordRequest, $hostIndex, $variables, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation validateBigCommercePasswordAsyncWithHttpInfo
     *
     * Validate BigCommerce Customer Password
     *
     * This operation contains host(s) defined in the OpenAPI spec. Use 'hostIndex' to select the host.
     * if needed, use the 'variables' parameter to pass variables to the host.
     * URL: https://{domain}.hub.loginradius.com
     *  Variables:
     *    - domain: LoginRadius Tenant Name
     *
     * @param  string $store BigCommerce store hash identifier (required)
     * @param  \LoginRadius\Sdk\Internal\OpenApi\Model\BigCommerceValidatePasswordRequest $bigCommerceValidatePasswordRequest (required)
     * @param  null|int $hostIndex Host index. Defaults to null. If null, then the library will use $this->hostIndex instead
     * @param  array $variables Associative array of variables to pass to the host. Defaults to empty array.
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['validateBigCommercePassword'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function validateBigCommercePasswordAsyncWithHttpInfo($store, $bigCommerceValidatePasswordRequest, ?int $hostIndex = null, array $variables = [], string $contentType = self::contentTypes['validateBigCommercePassword'][0])
    {
        $returnType = '\LoginRadius\Sdk\Internal\OpenApi\Model\BigCommerceValidatePasswordResponse';
        $request = $this->validateBigCommercePasswordRequest($store, $bigCommerceValidatePasswordRequest, $hostIndex, $variables, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'validateBigCommercePassword'
     *
    * This operation contains host(s) defined in the OpenAPI spec. Use 'hostIndex' to select the host.
    * if needed, use the 'variables' parameter to pass variables to the host.
     * URL: https://{domain}.hub.loginradius.com
     *  Variables:
    *    - domain: LoginRadius Tenant Name
     *
     * @param  string $store BigCommerce store hash identifier (required)
     * @param  \LoginRadius\Sdk\Internal\OpenApi\Model\BigCommerceValidatePasswordRequest $bigCommerceValidatePasswordRequest (required)
     * @param  null|int $hostIndex Host index. Defaults to null. If null, then the library will use $this->hostIndex instead
     * @param  array $variables Associative array of variables to pass to the host. Defaults to empty array.
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['validateBigCommercePassword'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function validateBigCommercePasswordRequest($store, $bigCommerceValidatePasswordRequest, ?int $hostIndex = null, array $variables = [], string $contentType = self::contentTypes['validateBigCommercePassword'][0])
    {

        // verify the required parameter 'store' is set
        if ($store === null || (is_array($store) && count($store) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $store when calling validateBigCommercePassword'
            );
        }

        // verify the required parameter 'bigCommerceValidatePasswordRequest' is set
        if ($bigCommerceValidatePasswordRequest === null || (is_array($bigCommerceValidatePasswordRequest) && count($bigCommerceValidatePasswordRequest) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $bigCommerceValidatePasswordRequest when calling validateBigCommercePassword'
            );
        }


        $resourcePath = '/sso/bigcommerce/api/validatepassword';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $store,
            'store', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            true // required
        ) ?? []);




        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (isset($bigCommerceValidatePasswordRequest)) {
            if (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the body
                $httpBody = \GuzzleHttp\Utils::jsonEncode(ObjectSerializer::sanitizeForSerialization($bigCommerceValidatePasswordRequest));
            } else {
                $httpBody = $bigCommerceValidatePasswordRequest;
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('apikey');
        if ($apiKey !== null) {
            $queryParams['apikey'] = $apiKey;
        }
        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('X-LoginRadius-ApiKey');
        if ($apiKey !== null) {
            $headers['X-LoginRadius-ApiKey'] = $apiKey;
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        # Preserve the original behavior of server indexing.
        if ($hostIndex === null) {
            $hostIndex = $this->hostIndex;
        }

        $hostSettings = $this->getHostSettingsForvalidateBigCommercePassword();

        if ($hostIndex < 0 || $hostIndex >= count($hostSettings)) {
            throw new \InvalidArgumentException("Invalid index {$hostIndex} when selecting the host. Must be less than ".count($hostSettings));
        }
        $operationHost = ($this->config->getLoginRadiusBaseUrlOverride() ?? Configuration::getHostString($hostSettings, $hostIndex, array_merge($this->config->getLoginRadiusServerVariables(), $variables)));
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'POST',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Returns an array of host settings for Operation validateBigCommercePassword
     *
     * @return array an array of host settings
     */
    protected function getHostSettingsForvalidateBigCommercePassword(): array
    {
        return [
            [
                "url" => "https://{domain}.hub.loginradius.com",
                "description" => "LoginRadius Hosted Plugins Server",
                "variables" => [
                    "domain" => [
                    "description" => "LoginRadius Tenant Name",
                    "default_value" => "example",
                    ]
                ]
            ]
        ];
    }

    /**
     * Create http client option
     *
     * @throws \RuntimeException on file opening failure
     * @return array of http client options
     */
    protected function createHttpClientOption()
    {
        $options = [];
        if ($this->config->getDebug()) {
            $options[RequestOptions::DEBUG] = fopen($this->config->getDebugFile(), 'a');
            if (!$options[RequestOptions::DEBUG]) {
                throw new \RuntimeException('Failed to open the debug file: ' . $this->config->getDebugFile());
            }
        }

        return $options;
    }
}
