<?php

/**
 * SMSTemplatesApi
 * PHP version 7.4
 *
 * @category Class
 * @package  LoginRadius\Sdk\Internal\OpenApi
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * LoginRadius API
 *
 * This is a LoginRadius API server. Which you can use to authenticate and manage the user.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@loginradius.com
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.10.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace LoginRadius\Sdk\Internal\OpenApi\Api;

use GuzzleHttp\Client;
use GuzzleHttp\ClientInterface;
use GuzzleHttp\Exception\ConnectException;
use GuzzleHttp\Exception\RequestException;
use GuzzleHttp\Psr7\MultipartStream;
use GuzzleHttp\Psr7\Request;
use GuzzleHttp\RequestOptions;
use LoginRadius\Sdk\Internal\OpenApi\ApiException;
use LoginRadius\Sdk\Internal\OpenApi\Configuration;
use LoginRadius\Sdk\Internal\OpenApi\HeaderSelector;
use LoginRadius\Sdk\Internal\OpenApi\ObjectSerializer;

/**
 * SMSTemplatesApi Class Doc Comment
 *
 * @category Class
 * @package  LoginRadius\Sdk\Internal\OpenApi
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class SMSTemplatesApi
{
    /**
     * @var ClientInterface
     */
    protected $client;

    /**
     * @var Configuration
     */
    protected $config;

    /**
     * @var HeaderSelector
     */
    protected $headerSelector;

    /**
     * @var int Host index
     */
    protected $hostIndex;

    /** @var string[] $contentTypes **/
    public const contentTypes = [
        'createSmsTemplate' => [
            'application/json',
        ],
        'deleteSmsTemplate' => [
            'application/json',
        ],
        'getSmsTemplates' => [
            'application/json',
        ],
        'updateSmsTemplate' => [
            'application/json',
        ],
    ];

    /**
     * @param ClientInterface $client
     * @param Configuration   $config
     * @param HeaderSelector  $selector
     * @param int             $hostIndex (Optional) host index to select the list of hosts if defined in the OpenAPI spec
     */
    public function __construct(
        ClientInterface $client = null,
        Configuration $config = null,
        HeaderSelector $selector = null,
        $hostIndex = 0
    ) {
        $this->client = $client ?: new Client();
        $this->config = $config ?: Configuration::getDefaultConfiguration();
        $this->headerSelector = $selector ?: new HeaderSelector();
        $this->hostIndex = $hostIndex;
    }

    /**
     * Set the host index
     *
     * @param int $hostIndex Host index (required)
     */
    public function setHostIndex($hostIndex): void
    {
        $this->hostIndex = $hostIndex;
    }

    /**
     * Get the host index
     *
     * @return int Host index
     */
    public function getHostIndex()
    {
        return $this->hostIndex;
    }

    /**
     * @return Configuration
     */
    public function getConfig()
    {
        return $this->config;
    }

    /**
     * Operation createSmsTemplate
     *
     * Create SMS template
     *
     * @param  \LoginRadius\Sdk\Internal\OpenApi\Model\SmsTemplate $smsTemplate smsTemplate (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['createSmsTemplate'] to see the possible values for this operation
     *
     * @throws \LoginRadius\Sdk\Internal\OpenApi\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \LoginRadius\Sdk\Internal\OpenApi\Model\SmsTemplate|\LoginRadius\Sdk\Internal\OpenApi\Model\ErrorResponse|\LoginRadius\Sdk\Internal\OpenApi\Model\ErrorResponse|\LoginRadius\Sdk\Internal\OpenApi\Model\ErrorResponse|\LoginRadius\Sdk\Internal\OpenApi\Model\ErrorResponse
     */
    public function createSmsTemplate($smsTemplate, string $contentType = self::contentTypes['createSmsTemplate'][0])
    {
        list($response) = $this->createSmsTemplateWithHttpInfo($smsTemplate, $contentType);
        return $response;
    }

    /**
     * Operation createSmsTemplateWithHttpInfo
     *
     * Create SMS template
     *
     * @param  \LoginRadius\Sdk\Internal\OpenApi\Model\SmsTemplate $smsTemplate (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['createSmsTemplate'] to see the possible values for this operation
     *
     * @throws \LoginRadius\Sdk\Internal\OpenApi\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \LoginRadius\Sdk\Internal\OpenApi\Model\SmsTemplate|\LoginRadius\Sdk\Internal\OpenApi\Model\ErrorResponse|\LoginRadius\Sdk\Internal\OpenApi\Model\ErrorResponse|\LoginRadius\Sdk\Internal\OpenApi\Model\ErrorResponse|\LoginRadius\Sdk\Internal\OpenApi\Model\ErrorResponse, HTTP status code, HTTP response headers (array of strings)
     */
    public function createSmsTemplateWithHttpInfo($smsTemplate, string $contentType = self::contentTypes['createSmsTemplate'][0])
    {
        $request = $this->createSmsTemplateRequest($smsTemplate, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            switch ($statusCode) {
                case 200:
                    if ('\LoginRadius\Sdk\Internal\OpenApi\Model\SmsTemplate' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ('\LoginRadius\Sdk\Internal\OpenApi\Model\SmsTemplate' !== 'string') {
                            try {
                                $content = json_decode($content, false, 512, JSON_THROW_ON_ERROR);
                            } catch (\JsonException $exception) {
                                throw new ApiException(
                                    sprintf(
                                        'Error JSON decoding server response (%s)',
                                        $request->getUri()
                                    ),
                                    $statusCode,
                                    $response->getHeaders(),
                                    $content
                                );
                            }
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\LoginRadius\Sdk\Internal\OpenApi\Model\SmsTemplate', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                case 400:
                    if ('\LoginRadius\Sdk\Internal\OpenApi\Model\ErrorResponse' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ('\LoginRadius\Sdk\Internal\OpenApi\Model\ErrorResponse' !== 'string') {
                            try {
                                $content = json_decode($content, false, 512, JSON_THROW_ON_ERROR);
                            } catch (\JsonException $exception) {
                                throw new ApiException(
                                    sprintf(
                                        'Error JSON decoding server response (%s)',
                                        $request->getUri()
                                    ),
                                    $statusCode,
                                    $response->getHeaders(),
                                    $content
                                );
                            }
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\LoginRadius\Sdk\Internal\OpenApi\Model\ErrorResponse', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                case 403:
                    if ('\LoginRadius\Sdk\Internal\OpenApi\Model\ErrorResponse' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ('\LoginRadius\Sdk\Internal\OpenApi\Model\ErrorResponse' !== 'string') {
                            try {
                                $content = json_decode($content, false, 512, JSON_THROW_ON_ERROR);
                            } catch (\JsonException $exception) {
                                throw new ApiException(
                                    sprintf(
                                        'Error JSON decoding server response (%s)',
                                        $request->getUri()
                                    ),
                                    $statusCode,
                                    $response->getHeaders(),
                                    $content
                                );
                            }
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\LoginRadius\Sdk\Internal\OpenApi\Model\ErrorResponse', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                case 409:
                    if ('\LoginRadius\Sdk\Internal\OpenApi\Model\ErrorResponse' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ('\LoginRadius\Sdk\Internal\OpenApi\Model\ErrorResponse' !== 'string') {
                            try {
                                $content = json_decode($content, false, 512, JSON_THROW_ON_ERROR);
                            } catch (\JsonException $exception) {
                                throw new ApiException(
                                    sprintf(
                                        'Error JSON decoding server response (%s)',
                                        $request->getUri()
                                    ),
                                    $statusCode,
                                    $response->getHeaders(),
                                    $content
                                );
                            }
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\LoginRadius\Sdk\Internal\OpenApi\Model\ErrorResponse', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                case 500:
                    if ('\LoginRadius\Sdk\Internal\OpenApi\Model\ErrorResponse' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ('\LoginRadius\Sdk\Internal\OpenApi\Model\ErrorResponse' !== 'string') {
                            try {
                                $content = json_decode($content, false, 512, JSON_THROW_ON_ERROR);
                            } catch (\JsonException $exception) {
                                throw new ApiException(
                                    sprintf(
                                        'Error JSON decoding server response (%s)',
                                        $request->getUri()
                                    ),
                                    $statusCode,
                                    $response->getHeaders(),
                                    $content
                                );
                            }
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\LoginRadius\Sdk\Internal\OpenApi\Model\ErrorResponse', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
            }

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            $returnType = '\LoginRadius\Sdk\Internal\OpenApi\Model\SmsTemplate';
            if ($returnType === '\SplFileObject') {
                $content = $response->getBody(); //stream goes to serializer
            } else {
                $content = (string) $response->getBody();
                if ($returnType !== 'string') {
                    try {
                        $content = json_decode($content, false, 512, JSON_THROW_ON_ERROR);
                    } catch (\JsonException $exception) {
                        throw new ApiException(
                            sprintf(
                                'Error JSON decoding server response (%s)',
                                $request->getUri()
                            ),
                            $statusCode,
                            $response->getHeaders(),
                            $content
                        );
                    }
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\LoginRadius\Sdk\Internal\OpenApi\Model\SmsTemplate',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 400:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\LoginRadius\Sdk\Internal\OpenApi\Model\ErrorResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 403:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\LoginRadius\Sdk\Internal\OpenApi\Model\ErrorResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 409:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\LoginRadius\Sdk\Internal\OpenApi\Model\ErrorResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 500:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\LoginRadius\Sdk\Internal\OpenApi\Model\ErrorResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation createSmsTemplateAsync
     *
     * Create SMS template
     *
     * @param  \LoginRadius\Sdk\Internal\OpenApi\Model\SmsTemplate $smsTemplate (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['createSmsTemplate'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function createSmsTemplateAsync($smsTemplate, string $contentType = self::contentTypes['createSmsTemplate'][0])
    {
        return $this->createSmsTemplateAsyncWithHttpInfo($smsTemplate, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation createSmsTemplateAsyncWithHttpInfo
     *
     * Create SMS template
     *
     * @param  \LoginRadius\Sdk\Internal\OpenApi\Model\SmsTemplate $smsTemplate (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['createSmsTemplate'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function createSmsTemplateAsyncWithHttpInfo($smsTemplate, string $contentType = self::contentTypes['createSmsTemplate'][0])
    {
        $returnType = '\LoginRadius\Sdk\Internal\OpenApi\Model\SmsTemplate';
        $request = $this->createSmsTemplateRequest($smsTemplate, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'createSmsTemplate'
     *
     * @param  \LoginRadius\Sdk\Internal\OpenApi\Model\SmsTemplate $smsTemplate (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['createSmsTemplate'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function createSmsTemplateRequest($smsTemplate, string $contentType = self::contentTypes['createSmsTemplate'][0])
    {

        // verify the required parameter 'smsTemplate' is set
        if ($smsTemplate === null || (is_array($smsTemplate) && count($smsTemplate) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $smsTemplate when calling createSmsTemplate'
            );
        }


        $resourcePath = '/v2/manage/smstemplates';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;





        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (isset($smsTemplate)) {
            if (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the body
                $httpBody = \GuzzleHttp\Utils::jsonEncode(ObjectSerializer::sanitizeForSerialization($smsTemplate));
            } else {
                $httpBody = $smsTemplate;
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires Bearer (JWT) authentication (access token)
        if (!empty($this->config->getAccessToken())) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'POST',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation deleteSmsTemplate
     *
     * Delete SMS template
     *
     * @param  string $templateType The type of SMS template to delete. (required)
     * @param  \LoginRadius\Sdk\Internal\OpenApi\Model\DeleteSmsTemplateModel $deleteSmsTemplateModel deleteSmsTemplateModel (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['deleteSmsTemplate'] to see the possible values for this operation
     *
     * @throws \LoginRadius\Sdk\Internal\OpenApi\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \LoginRadius\Sdk\Internal\OpenApi\Model\DeleteResponse|\LoginRadius\Sdk\Internal\OpenApi\Model\ErrorResponse|\LoginRadius\Sdk\Internal\OpenApi\Model\ErrorResponse|\LoginRadius\Sdk\Internal\OpenApi\Model\ErrorResponse|\LoginRadius\Sdk\Internal\OpenApi\Model\ErrorResponse
     */
    public function deleteSmsTemplate($templateType, $deleteSmsTemplateModel, string $contentType = self::contentTypes['deleteSmsTemplate'][0])
    {
        list($response) = $this->deleteSmsTemplateWithHttpInfo($templateType, $deleteSmsTemplateModel, $contentType);
        return $response;
    }

    /**
     * Operation deleteSmsTemplateWithHttpInfo
     *
     * Delete SMS template
     *
     * @param  string $templateType The type of SMS template to delete. (required)
     * @param  \LoginRadius\Sdk\Internal\OpenApi\Model\DeleteSmsTemplateModel $deleteSmsTemplateModel (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['deleteSmsTemplate'] to see the possible values for this operation
     *
     * @throws \LoginRadius\Sdk\Internal\OpenApi\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \LoginRadius\Sdk\Internal\OpenApi\Model\DeleteResponse|\LoginRadius\Sdk\Internal\OpenApi\Model\ErrorResponse|\LoginRadius\Sdk\Internal\OpenApi\Model\ErrorResponse|\LoginRadius\Sdk\Internal\OpenApi\Model\ErrorResponse|\LoginRadius\Sdk\Internal\OpenApi\Model\ErrorResponse, HTTP status code, HTTP response headers (array of strings)
     */
    public function deleteSmsTemplateWithHttpInfo($templateType, $deleteSmsTemplateModel, string $contentType = self::contentTypes['deleteSmsTemplate'][0])
    {
        $request = $this->deleteSmsTemplateRequest($templateType, $deleteSmsTemplateModel, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            switch ($statusCode) {
                case 200:
                    if ('\LoginRadius\Sdk\Internal\OpenApi\Model\DeleteResponse' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ('\LoginRadius\Sdk\Internal\OpenApi\Model\DeleteResponse' !== 'string') {
                            try {
                                $content = json_decode($content, false, 512, JSON_THROW_ON_ERROR);
                            } catch (\JsonException $exception) {
                                throw new ApiException(
                                    sprintf(
                                        'Error JSON decoding server response (%s)',
                                        $request->getUri()
                                    ),
                                    $statusCode,
                                    $response->getHeaders(),
                                    $content
                                );
                            }
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\LoginRadius\Sdk\Internal\OpenApi\Model\DeleteResponse', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                case 400:
                    if ('\LoginRadius\Sdk\Internal\OpenApi\Model\ErrorResponse' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ('\LoginRadius\Sdk\Internal\OpenApi\Model\ErrorResponse' !== 'string') {
                            try {
                                $content = json_decode($content, false, 512, JSON_THROW_ON_ERROR);
                            } catch (\JsonException $exception) {
                                throw new ApiException(
                                    sprintf(
                                        'Error JSON decoding server response (%s)',
                                        $request->getUri()
                                    ),
                                    $statusCode,
                                    $response->getHeaders(),
                                    $content
                                );
                            }
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\LoginRadius\Sdk\Internal\OpenApi\Model\ErrorResponse', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                case 403:
                    if ('\LoginRadius\Sdk\Internal\OpenApi\Model\ErrorResponse' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ('\LoginRadius\Sdk\Internal\OpenApi\Model\ErrorResponse' !== 'string') {
                            try {
                                $content = json_decode($content, false, 512, JSON_THROW_ON_ERROR);
                            } catch (\JsonException $exception) {
                                throw new ApiException(
                                    sprintf(
                                        'Error JSON decoding server response (%s)',
                                        $request->getUri()
                                    ),
                                    $statusCode,
                                    $response->getHeaders(),
                                    $content
                                );
                            }
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\LoginRadius\Sdk\Internal\OpenApi\Model\ErrorResponse', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                case 404:
                    if ('\LoginRadius\Sdk\Internal\OpenApi\Model\ErrorResponse' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ('\LoginRadius\Sdk\Internal\OpenApi\Model\ErrorResponse' !== 'string') {
                            try {
                                $content = json_decode($content, false, 512, JSON_THROW_ON_ERROR);
                            } catch (\JsonException $exception) {
                                throw new ApiException(
                                    sprintf(
                                        'Error JSON decoding server response (%s)',
                                        $request->getUri()
                                    ),
                                    $statusCode,
                                    $response->getHeaders(),
                                    $content
                                );
                            }
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\LoginRadius\Sdk\Internal\OpenApi\Model\ErrorResponse', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                case 500:
                    if ('\LoginRadius\Sdk\Internal\OpenApi\Model\ErrorResponse' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ('\LoginRadius\Sdk\Internal\OpenApi\Model\ErrorResponse' !== 'string') {
                            try {
                                $content = json_decode($content, false, 512, JSON_THROW_ON_ERROR);
                            } catch (\JsonException $exception) {
                                throw new ApiException(
                                    sprintf(
                                        'Error JSON decoding server response (%s)',
                                        $request->getUri()
                                    ),
                                    $statusCode,
                                    $response->getHeaders(),
                                    $content
                                );
                            }
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\LoginRadius\Sdk\Internal\OpenApi\Model\ErrorResponse', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
            }

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            $returnType = '\LoginRadius\Sdk\Internal\OpenApi\Model\DeleteResponse';
            if ($returnType === '\SplFileObject') {
                $content = $response->getBody(); //stream goes to serializer
            } else {
                $content = (string) $response->getBody();
                if ($returnType !== 'string') {
                    try {
                        $content = json_decode($content, false, 512, JSON_THROW_ON_ERROR);
                    } catch (\JsonException $exception) {
                        throw new ApiException(
                            sprintf(
                                'Error JSON decoding server response (%s)',
                                $request->getUri()
                            ),
                            $statusCode,
                            $response->getHeaders(),
                            $content
                        );
                    }
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\LoginRadius\Sdk\Internal\OpenApi\Model\DeleteResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 400:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\LoginRadius\Sdk\Internal\OpenApi\Model\ErrorResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 403:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\LoginRadius\Sdk\Internal\OpenApi\Model\ErrorResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 404:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\LoginRadius\Sdk\Internal\OpenApi\Model\ErrorResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 500:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\LoginRadius\Sdk\Internal\OpenApi\Model\ErrorResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation deleteSmsTemplateAsync
     *
     * Delete SMS template
     *
     * @param  string $templateType The type of SMS template to delete. (required)
     * @param  \LoginRadius\Sdk\Internal\OpenApi\Model\DeleteSmsTemplateModel $deleteSmsTemplateModel (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['deleteSmsTemplate'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function deleteSmsTemplateAsync($templateType, $deleteSmsTemplateModel, string $contentType = self::contentTypes['deleteSmsTemplate'][0])
    {
        return $this->deleteSmsTemplateAsyncWithHttpInfo($templateType, $deleteSmsTemplateModel, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation deleteSmsTemplateAsyncWithHttpInfo
     *
     * Delete SMS template
     *
     * @param  string $templateType The type of SMS template to delete. (required)
     * @param  \LoginRadius\Sdk\Internal\OpenApi\Model\DeleteSmsTemplateModel $deleteSmsTemplateModel (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['deleteSmsTemplate'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function deleteSmsTemplateAsyncWithHttpInfo($templateType, $deleteSmsTemplateModel, string $contentType = self::contentTypes['deleteSmsTemplate'][0])
    {
        $returnType = '\LoginRadius\Sdk\Internal\OpenApi\Model\DeleteResponse';
        $request = $this->deleteSmsTemplateRequest($templateType, $deleteSmsTemplateModel, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'deleteSmsTemplate'
     *
     * @param  string $templateType The type of SMS template to delete. (required)
     * @param  \LoginRadius\Sdk\Internal\OpenApi\Model\DeleteSmsTemplateModel $deleteSmsTemplateModel (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['deleteSmsTemplate'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function deleteSmsTemplateRequest($templateType, $deleteSmsTemplateModel, string $contentType = self::contentTypes['deleteSmsTemplate'][0])
    {

        // verify the required parameter 'templateType' is set
        if ($templateType === null || (is_array($templateType) && count($templateType) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $templateType when calling deleteSmsTemplate'
            );
        }

        // verify the required parameter 'deleteSmsTemplateModel' is set
        if ($deleteSmsTemplateModel === null || (is_array($deleteSmsTemplateModel) && count($deleteSmsTemplateModel) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $deleteSmsTemplateModel when calling deleteSmsTemplate'
            );
        }


        $resourcePath = '/v2/manage/sms-templates/{templateType}';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;



        // path params
        if ($templateType !== null) {
            $resourcePath = str_replace(
                '{' . 'templateType' . '}',
                ObjectSerializer::toPathValue($templateType),
                $resourcePath
            );
        }


        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (isset($deleteSmsTemplateModel)) {
            if (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the body
                $httpBody = \GuzzleHttp\Utils::jsonEncode(ObjectSerializer::sanitizeForSerialization($deleteSmsTemplateModel));
            } else {
                $httpBody = $deleteSmsTemplateModel;
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires Bearer (JWT) authentication (access token)
        if (!empty($this->config->getAccessToken())) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'DELETE',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation getSmsTemplates
     *
     * List SMS templates
     *
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getSmsTemplates'] to see the possible values for this operation
     *
     * @throws \LoginRadius\Sdk\Internal\OpenApi\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \LoginRadius\Sdk\Internal\OpenApi\Model\GetSmsTemplates200Response|\LoginRadius\Sdk\Internal\OpenApi\Model\ErrorResponse|\LoginRadius\Sdk\Internal\OpenApi\Model\ErrorResponse
     */
    public function getSmsTemplates(string $contentType = self::contentTypes['getSmsTemplates'][0])
    {
        list($response) = $this->getSmsTemplatesWithHttpInfo($contentType);
        return $response;
    }

    /**
     * Operation getSmsTemplatesWithHttpInfo
     *
     * List SMS templates
     *
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getSmsTemplates'] to see the possible values for this operation
     *
     * @throws \LoginRadius\Sdk\Internal\OpenApi\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \LoginRadius\Sdk\Internal\OpenApi\Model\GetSmsTemplates200Response|\LoginRadius\Sdk\Internal\OpenApi\Model\ErrorResponse|\LoginRadius\Sdk\Internal\OpenApi\Model\ErrorResponse, HTTP status code, HTTP response headers (array of strings)
     */
    public function getSmsTemplatesWithHttpInfo(string $contentType = self::contentTypes['getSmsTemplates'][0])
    {
        $request = $this->getSmsTemplatesRequest($contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            switch ($statusCode) {
                case 200:
                    if ('\LoginRadius\Sdk\Internal\OpenApi\Model\GetSmsTemplates200Response' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ('\LoginRadius\Sdk\Internal\OpenApi\Model\GetSmsTemplates200Response' !== 'string') {
                            try {
                                $content = json_decode($content, false, 512, JSON_THROW_ON_ERROR);
                            } catch (\JsonException $exception) {
                                throw new ApiException(
                                    sprintf(
                                        'Error JSON decoding server response (%s)',
                                        $request->getUri()
                                    ),
                                    $statusCode,
                                    $response->getHeaders(),
                                    $content
                                );
                            }
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\LoginRadius\Sdk\Internal\OpenApi\Model\GetSmsTemplates200Response', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                case 403:
                    if ('\LoginRadius\Sdk\Internal\OpenApi\Model\ErrorResponse' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ('\LoginRadius\Sdk\Internal\OpenApi\Model\ErrorResponse' !== 'string') {
                            try {
                                $content = json_decode($content, false, 512, JSON_THROW_ON_ERROR);
                            } catch (\JsonException $exception) {
                                throw new ApiException(
                                    sprintf(
                                        'Error JSON decoding server response (%s)',
                                        $request->getUri()
                                    ),
                                    $statusCode,
                                    $response->getHeaders(),
                                    $content
                                );
                            }
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\LoginRadius\Sdk\Internal\OpenApi\Model\ErrorResponse', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                case 500:
                    if ('\LoginRadius\Sdk\Internal\OpenApi\Model\ErrorResponse' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ('\LoginRadius\Sdk\Internal\OpenApi\Model\ErrorResponse' !== 'string') {
                            try {
                                $content = json_decode($content, false, 512, JSON_THROW_ON_ERROR);
                            } catch (\JsonException $exception) {
                                throw new ApiException(
                                    sprintf(
                                        'Error JSON decoding server response (%s)',
                                        $request->getUri()
                                    ),
                                    $statusCode,
                                    $response->getHeaders(),
                                    $content
                                );
                            }
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\LoginRadius\Sdk\Internal\OpenApi\Model\ErrorResponse', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
            }

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            $returnType = '\LoginRadius\Sdk\Internal\OpenApi\Model\GetSmsTemplates200Response';
            if ($returnType === '\SplFileObject') {
                $content = $response->getBody(); //stream goes to serializer
            } else {
                $content = (string) $response->getBody();
                if ($returnType !== 'string') {
                    try {
                        $content = json_decode($content, false, 512, JSON_THROW_ON_ERROR);
                    } catch (\JsonException $exception) {
                        throw new ApiException(
                            sprintf(
                                'Error JSON decoding server response (%s)',
                                $request->getUri()
                            ),
                            $statusCode,
                            $response->getHeaders(),
                            $content
                        );
                    }
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\LoginRadius\Sdk\Internal\OpenApi\Model\GetSmsTemplates200Response',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 403:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\LoginRadius\Sdk\Internal\OpenApi\Model\ErrorResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 500:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\LoginRadius\Sdk\Internal\OpenApi\Model\ErrorResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation getSmsTemplatesAsync
     *
     * List SMS templates
     *
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getSmsTemplates'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getSmsTemplatesAsync(string $contentType = self::contentTypes['getSmsTemplates'][0])
    {
        return $this->getSmsTemplatesAsyncWithHttpInfo($contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation getSmsTemplatesAsyncWithHttpInfo
     *
     * List SMS templates
     *
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getSmsTemplates'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getSmsTemplatesAsyncWithHttpInfo(string $contentType = self::contentTypes['getSmsTemplates'][0])
    {
        $returnType = '\LoginRadius\Sdk\Internal\OpenApi\Model\GetSmsTemplates200Response';
        $request = $this->getSmsTemplatesRequest($contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'getSmsTemplates'
     *
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getSmsTemplates'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function getSmsTemplatesRequest(string $contentType = self::contentTypes['getSmsTemplates'][0])
    {


        $resourcePath = '/v2/manage/smstemplates';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;





        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires Bearer (JWT) authentication (access token)
        if (!empty($this->config->getAccessToken())) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'GET',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation updateSmsTemplate
     *
     * Update SMS template
     *
     * @param  string $templateType The type of SMS template to delete. (required)
     * @param  \LoginRadius\Sdk\Internal\OpenApi\Model\UpdateSmsTemplateModel $updateSmsTemplateModel updateSmsTemplateModel (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['updateSmsTemplate'] to see the possible values for this operation
     *
     * @throws \LoginRadius\Sdk\Internal\OpenApi\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \LoginRadius\Sdk\Internal\OpenApi\Model\SmsTemplate|\LoginRadius\Sdk\Internal\OpenApi\Model\ErrorResponse|\LoginRadius\Sdk\Internal\OpenApi\Model\ErrorResponse|\LoginRadius\Sdk\Internal\OpenApi\Model\ErrorResponse|\LoginRadius\Sdk\Internal\OpenApi\Model\ErrorResponse
     */
    public function updateSmsTemplate($templateType, $updateSmsTemplateModel, string $contentType = self::contentTypes['updateSmsTemplate'][0])
    {
        list($response) = $this->updateSmsTemplateWithHttpInfo($templateType, $updateSmsTemplateModel, $contentType);
        return $response;
    }

    /**
     * Operation updateSmsTemplateWithHttpInfo
     *
     * Update SMS template
     *
     * @param  string $templateType The type of SMS template to delete. (required)
     * @param  \LoginRadius\Sdk\Internal\OpenApi\Model\UpdateSmsTemplateModel $updateSmsTemplateModel (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['updateSmsTemplate'] to see the possible values for this operation
     *
     * @throws \LoginRadius\Sdk\Internal\OpenApi\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \LoginRadius\Sdk\Internal\OpenApi\Model\SmsTemplate|\LoginRadius\Sdk\Internal\OpenApi\Model\ErrorResponse|\LoginRadius\Sdk\Internal\OpenApi\Model\ErrorResponse|\LoginRadius\Sdk\Internal\OpenApi\Model\ErrorResponse|\LoginRadius\Sdk\Internal\OpenApi\Model\ErrorResponse, HTTP status code, HTTP response headers (array of strings)
     */
    public function updateSmsTemplateWithHttpInfo($templateType, $updateSmsTemplateModel, string $contentType = self::contentTypes['updateSmsTemplate'][0])
    {
        $request = $this->updateSmsTemplateRequest($templateType, $updateSmsTemplateModel, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            switch ($statusCode) {
                case 200:
                    if ('\LoginRadius\Sdk\Internal\OpenApi\Model\SmsTemplate' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ('\LoginRadius\Sdk\Internal\OpenApi\Model\SmsTemplate' !== 'string') {
                            try {
                                $content = json_decode($content, false, 512, JSON_THROW_ON_ERROR);
                            } catch (\JsonException $exception) {
                                throw new ApiException(
                                    sprintf(
                                        'Error JSON decoding server response (%s)',
                                        $request->getUri()
                                    ),
                                    $statusCode,
                                    $response->getHeaders(),
                                    $content
                                );
                            }
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\LoginRadius\Sdk\Internal\OpenApi\Model\SmsTemplate', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                case 400:
                    if ('\LoginRadius\Sdk\Internal\OpenApi\Model\ErrorResponse' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ('\LoginRadius\Sdk\Internal\OpenApi\Model\ErrorResponse' !== 'string') {
                            try {
                                $content = json_decode($content, false, 512, JSON_THROW_ON_ERROR);
                            } catch (\JsonException $exception) {
                                throw new ApiException(
                                    sprintf(
                                        'Error JSON decoding server response (%s)',
                                        $request->getUri()
                                    ),
                                    $statusCode,
                                    $response->getHeaders(),
                                    $content
                                );
                            }
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\LoginRadius\Sdk\Internal\OpenApi\Model\ErrorResponse', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                case 403:
                    if ('\LoginRadius\Sdk\Internal\OpenApi\Model\ErrorResponse' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ('\LoginRadius\Sdk\Internal\OpenApi\Model\ErrorResponse' !== 'string') {
                            try {
                                $content = json_decode($content, false, 512, JSON_THROW_ON_ERROR);
                            } catch (\JsonException $exception) {
                                throw new ApiException(
                                    sprintf(
                                        'Error JSON decoding server response (%s)',
                                        $request->getUri()
                                    ),
                                    $statusCode,
                                    $response->getHeaders(),
                                    $content
                                );
                            }
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\LoginRadius\Sdk\Internal\OpenApi\Model\ErrorResponse', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                case 404:
                    if ('\LoginRadius\Sdk\Internal\OpenApi\Model\ErrorResponse' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ('\LoginRadius\Sdk\Internal\OpenApi\Model\ErrorResponse' !== 'string') {
                            try {
                                $content = json_decode($content, false, 512, JSON_THROW_ON_ERROR);
                            } catch (\JsonException $exception) {
                                throw new ApiException(
                                    sprintf(
                                        'Error JSON decoding server response (%s)',
                                        $request->getUri()
                                    ),
                                    $statusCode,
                                    $response->getHeaders(),
                                    $content
                                );
                            }
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\LoginRadius\Sdk\Internal\OpenApi\Model\ErrorResponse', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                case 500:
                    if ('\LoginRadius\Sdk\Internal\OpenApi\Model\ErrorResponse' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ('\LoginRadius\Sdk\Internal\OpenApi\Model\ErrorResponse' !== 'string') {
                            try {
                                $content = json_decode($content, false, 512, JSON_THROW_ON_ERROR);
                            } catch (\JsonException $exception) {
                                throw new ApiException(
                                    sprintf(
                                        'Error JSON decoding server response (%s)',
                                        $request->getUri()
                                    ),
                                    $statusCode,
                                    $response->getHeaders(),
                                    $content
                                );
                            }
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\LoginRadius\Sdk\Internal\OpenApi\Model\ErrorResponse', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
            }

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            $returnType = '\LoginRadius\Sdk\Internal\OpenApi\Model\SmsTemplate';
            if ($returnType === '\SplFileObject') {
                $content = $response->getBody(); //stream goes to serializer
            } else {
                $content = (string) $response->getBody();
                if ($returnType !== 'string') {
                    try {
                        $content = json_decode($content, false, 512, JSON_THROW_ON_ERROR);
                    } catch (\JsonException $exception) {
                        throw new ApiException(
                            sprintf(
                                'Error JSON decoding server response (%s)',
                                $request->getUri()
                            ),
                            $statusCode,
                            $response->getHeaders(),
                            $content
                        );
                    }
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\LoginRadius\Sdk\Internal\OpenApi\Model\SmsTemplate',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 400:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\LoginRadius\Sdk\Internal\OpenApi\Model\ErrorResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 403:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\LoginRadius\Sdk\Internal\OpenApi\Model\ErrorResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 404:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\LoginRadius\Sdk\Internal\OpenApi\Model\ErrorResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 500:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\LoginRadius\Sdk\Internal\OpenApi\Model\ErrorResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation updateSmsTemplateAsync
     *
     * Update SMS template
     *
     * @param  string $templateType The type of SMS template to delete. (required)
     * @param  \LoginRadius\Sdk\Internal\OpenApi\Model\UpdateSmsTemplateModel $updateSmsTemplateModel (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['updateSmsTemplate'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function updateSmsTemplateAsync($templateType, $updateSmsTemplateModel, string $contentType = self::contentTypes['updateSmsTemplate'][0])
    {
        return $this->updateSmsTemplateAsyncWithHttpInfo($templateType, $updateSmsTemplateModel, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation updateSmsTemplateAsyncWithHttpInfo
     *
     * Update SMS template
     *
     * @param  string $templateType The type of SMS template to delete. (required)
     * @param  \LoginRadius\Sdk\Internal\OpenApi\Model\UpdateSmsTemplateModel $updateSmsTemplateModel (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['updateSmsTemplate'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function updateSmsTemplateAsyncWithHttpInfo($templateType, $updateSmsTemplateModel, string $contentType = self::contentTypes['updateSmsTemplate'][0])
    {
        $returnType = '\LoginRadius\Sdk\Internal\OpenApi\Model\SmsTemplate';
        $request = $this->updateSmsTemplateRequest($templateType, $updateSmsTemplateModel, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'updateSmsTemplate'
     *
     * @param  string $templateType The type of SMS template to delete. (required)
     * @param  \LoginRadius\Sdk\Internal\OpenApi\Model\UpdateSmsTemplateModel $updateSmsTemplateModel (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['updateSmsTemplate'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function updateSmsTemplateRequest($templateType, $updateSmsTemplateModel, string $contentType = self::contentTypes['updateSmsTemplate'][0])
    {

        // verify the required parameter 'templateType' is set
        if ($templateType === null || (is_array($templateType) && count($templateType) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $templateType when calling updateSmsTemplate'
            );
        }

        // verify the required parameter 'updateSmsTemplateModel' is set
        if ($updateSmsTemplateModel === null || (is_array($updateSmsTemplateModel) && count($updateSmsTemplateModel) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $updateSmsTemplateModel when calling updateSmsTemplate'
            );
        }


        $resourcePath = '/v2/manage/sms-templates/{templateType}';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;



        // path params
        if ($templateType !== null) {
            $resourcePath = str_replace(
                '{' . 'templateType' . '}',
                ObjectSerializer::toPathValue($templateType),
                $resourcePath
            );
        }


        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (isset($updateSmsTemplateModel)) {
            if (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the body
                $httpBody = \GuzzleHttp\Utils::jsonEncode(ObjectSerializer::sanitizeForSerialization($updateSmsTemplateModel));
            } else {
                $httpBody = $updateSmsTemplateModel;
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires Bearer (JWT) authentication (access token)
        if (!empty($this->config->getAccessToken())) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'PUT',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Create http client option
     *
     * @throws \RuntimeException on file opening failure
     * @return array of http client options
     */
    protected function createHttpClientOption()
    {
        $options = [];
        if ($this->config->getDebug()) {
            $options[RequestOptions::DEBUG] = fopen($this->config->getDebugFile(), 'a');
            if (!$options[RequestOptions::DEBUG]) {
                throw new \RuntimeException('Failed to open the debug file: ' . $this->config->getDebugFile());
            }
        }

        return $options;
    }
}
