<?php

/**
 * ConsentLog
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  LoginRadius\Sdk\Internal\OpenApi
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * LoginRadius API
 *
 * This is a LoginRadius API server. Which you can use to authenticate and manage the user.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@loginradius.com
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.10.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace LoginRadius\Sdk\Internal\OpenApi\Model;

use \ArrayAccess;
use \LoginRadius\Sdk\Internal\OpenApi\ObjectSerializer;

/**
 * ConsentLog Class Doc Comment
 *
 * @category Class
 * @package  LoginRadius\Sdk\Internal\OpenApi
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class ConsentLog implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'ConsentLog';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'updateType' => 'string',
        'userAgent' => 'string',
        'iP' => 'string',
        'host' => 'string',
        'loggedOnDate' => '\DateTime',
        'currentConsentFormsVersions' => '\LoginRadius\Sdk\Internal\OpenApi\Model\ConsentVersion[]',
        'consentLogs' => '\LoginRadius\Sdk\Internal\OpenApi\Model\ConsentProfileLog[]',
        'id' => 'string'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'updateType' => null,
        'userAgent' => null,
        'iP' => null,
        'host' => null,
        'loggedOnDate' => 'date-time',
        'currentConsentFormsVersions' => null,
        'consentLogs' => null,
        'id' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'updateType' => true,
        'userAgent' => true,
        'iP' => true,
        'host' => true,
        'loggedOnDate' => true,
        'currentConsentFormsVersions' => false,
        'consentLogs' => true,
        'id' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'updateType' => 'UpdateType',
        'userAgent' => 'UserAgent',
        'iP' => 'IP',
        'host' => 'Host',
        'loggedOnDate' => 'LoggedOnDate',
        'currentConsentFormsVersions' => 'CurrentConsentFormsVersions',
        'consentLogs' => 'ConsentLogs',
        'id' => 'Id'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'updateType' => 'setUpdateType',
        'userAgent' => 'setUserAgent',
        'iP' => 'setIP',
        'host' => 'setHost',
        'loggedOnDate' => 'setLoggedOnDate',
        'currentConsentFormsVersions' => 'setCurrentConsentFormsVersions',
        'consentLogs' => 'setConsentLogs',
        'id' => 'setId'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'updateType' => 'getUpdateType',
        'userAgent' => 'getUserAgent',
        'iP' => 'getIP',
        'host' => 'getHost',
        'loggedOnDate' => 'getLoggedOnDate',
        'currentConsentFormsVersions' => 'getCurrentConsentFormsVersions',
        'consentLogs' => 'getConsentLogs',
        'id' => 'getId'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->setIfExists('updateType', $data ?? [], null);
        $this->setIfExists('userAgent', $data ?? [], null);
        $this->setIfExists('iP', $data ?? [], null);
        $this->setIfExists('host', $data ?? [], null);
        $this->setIfExists('loggedOnDate', $data ?? [], null);
        $this->setIfExists('currentConsentFormsVersions', $data ?? [], null);
        $this->setIfExists('consentLogs', $data ?? [], null);
        $this->setIfExists('id', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets updateType
     *
     * @return string|null
     */
    public function getUpdateType()
    {
        return $this->container['updateType'];
    }

    /**
     * Sets updateType
     *
     * @param string|null $updateType Type of update performed
     *
     * @return self
     */
    public function setUpdateType($updateType)
    {
        if (is_null($updateType)) {
            array_push($this->openAPINullablesSetToNull, 'updateType');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('updateType', $nullablesSetToNull, true);
            if ($index !== false) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['updateType'] = $updateType;

        return $this;
    }

    /**
     * Gets userAgent
     *
     * @return string|null
     */
    public function getUserAgent()
    {
        return $this->container['userAgent'];
    }

    /**
     * Sets userAgent
     *
     * @param string|null $userAgent User agent string
     *
     * @return self
     */
    public function setUserAgent($userAgent)
    {
        if (is_null($userAgent)) {
            array_push($this->openAPINullablesSetToNull, 'userAgent');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('userAgent', $nullablesSetToNull, true);
            if ($index !== false) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['userAgent'] = $userAgent;

        return $this;
    }

    /**
     * Gets iP
     *
     * @return string|null
     */
    public function getIP()
    {
        return $this->container['iP'];
    }

    /**
     * Sets iP
     *
     * @param string|null $iP IP address of the User
     *
     * @return self
     */
    public function setIP($iP)
    {
        if (is_null($iP)) {
            array_push($this->openAPINullablesSetToNull, 'iP');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('iP', $nullablesSetToNull, true);
            if ($index !== false) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['iP'] = $iP;

        return $this;
    }

    /**
     * Gets host
     *
     * @return string|null
     */
    public function getHost()
    {
        return $this->container['host'];
    }

    /**
     * Sets host
     *
     * @param string|null $host Host information
     *
     * @return self
     */
    public function setHost($host)
    {
        if (is_null($host)) {
            array_push($this->openAPINullablesSetToNull, 'host');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('host', $nullablesSetToNull, true);
            if ($index !== false) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['host'] = $host;

        return $this;
    }

    /**
     * Gets loggedOnDate
     *
     * @return \DateTime|null
     */
    public function getLoggedOnDate()
    {
        return $this->container['loggedOnDate'];
    }

    /**
     * Sets loggedOnDate
     *
     * @param \DateTime|null $loggedOnDate Date and time when the log was created
     *
     * @return self
     */
    public function setLoggedOnDate($loggedOnDate)
    {
        if (is_null($loggedOnDate)) {
            array_push($this->openAPINullablesSetToNull, 'loggedOnDate');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('loggedOnDate', $nullablesSetToNull, true);
            if ($index !== false) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['loggedOnDate'] = $loggedOnDate;

        return $this;
    }

    /**
     * Gets currentConsentFormsVersions
     *
     * @return \LoginRadius\Sdk\Internal\OpenApi\Model\ConsentVersion[]|null
     */
    public function getCurrentConsentFormsVersions()
    {
        return $this->container['currentConsentFormsVersions'];
    }

    /**
     * Sets currentConsentFormsVersions
     *
     * @param \LoginRadius\Sdk\Internal\OpenApi\Model\ConsentVersion[]|null $currentConsentFormsVersions List of current consent form versions
     *
     * @return self
     */
    public function setCurrentConsentFormsVersions($currentConsentFormsVersions)
    {
        if (is_null($currentConsentFormsVersions)) {
            throw new \InvalidArgumentException('non-nullable currentConsentFormsVersions cannot be null');
        }
        $this->container['currentConsentFormsVersions'] = $currentConsentFormsVersions;

        return $this;
    }

    /**
     * Gets consentLogs
     *
     * @return \LoginRadius\Sdk\Internal\OpenApi\Model\ConsentProfileLog[]|null
     */
    public function getConsentLogs()
    {
        return $this->container['consentLogs'];
    }

    /**
     * Sets consentLogs
     *
     * @param \LoginRadius\Sdk\Internal\OpenApi\Model\ConsentProfileLog[]|null $consentLogs List of consent profile logs
     *
     * @return self
     */
    public function setConsentLogs($consentLogs)
    {
        if (is_null($consentLogs)) {
            array_push($this->openAPINullablesSetToNull, 'consentLogs');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('consentLogs', $nullablesSetToNull, true);
            if ($index !== false) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['consentLogs'] = $consentLogs;

        return $this;
    }

    /**
     * Gets id
     *
     * @return string|null
     */
    public function getId()
    {
        return $this->container['id'];
    }

    /**
     * Sets id
     *
     * @param string|null $id ObjectId (MongoDB) of the log entry
     *
     * @return self
     */
    public function setId($id)
    {
        if (is_null($id)) {
            throw new \InvalidArgumentException('non-nullable id cannot be null');
        }
        $this->container['id'] = $id;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
        return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


