<?php

/**
 * JwtSpConfig
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  LoginRadius\Sdk\Internal\OpenApi
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * LoginRadius API
 *
 * This is a LoginRadius API server. Which you can use to authenticate and manage the user.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@loginradius.com
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.10.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace LoginRadius\Sdk\Internal\OpenApi\Model;

use \ArrayAccess;
use \LoginRadius\Sdk\Internal\OpenApi\ObjectSerializer;

/**
 * JwtSpConfig Class Doc Comment
 *
 * @category Class
 * @package  LoginRadius\Sdk\Internal\OpenApi
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class JwtSpConfig implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'JwtSpConfig';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'id' => 'string',
        'isActive' => 'bool',
        'appId' => 'int',
        'appName' => 'string',
        'algo' => 'string',
        'mapping' => 'array<string,string>',
        'key' => 'string',
        'tokenQueryParameterName' => 'string',
        'clockSkew' => 'int',
        'loginUrl' => 'string',
        'issuer' => '\LoginRadius\Sdk\Internal\OpenApi\Model\JwtIssuerValidation',
        'subject' => '\LoginRadius\Sdk\Internal\OpenApi\Model\JwtValidation',
        'audience' => '\LoginRadius\Sdk\Internal\OpenApi\Model\JwtAudienceValidation',
        'expirationTimeDifference' => 'int',
        'useAuthorizationHeader' => 'bool',
        'notBefore' => '\LoginRadius\Sdk\Internal\OpenApi\Model\JwtValidation',
        'expiration' => '\LoginRadius\Sdk\Internal\OpenApi\Model\JwtValidation',
        'jWKSUrl' => 'string',
        'updateEmailProfile' => 'bool',
        'raasUpdateFields' => 'string[]',
        'domain' => 'string',
        'enableAutoLookUp' => 'bool',
        'version' => 'string',
        'listInInterface' => 'bool',
        'createdDate' => '\DateTime',
        'lastModifiedDate' => '\DateTime'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'id' => 'objectId',
        'isActive' => null,
        'appId' => null,
        'appName' => null,
        'algo' => null,
        'mapping' => null,
        'key' => null,
        'tokenQueryParameterName' => null,
        'clockSkew' => null,
        'loginUrl' => null,
        'issuer' => null,
        'subject' => null,
        'audience' => null,
        'expirationTimeDifference' => null,
        'useAuthorizationHeader' => null,
        'notBefore' => null,
        'expiration' => null,
        'jWKSUrl' => null,
        'updateEmailProfile' => null,
        'raasUpdateFields' => null,
        'domain' => null,
        'enableAutoLookUp' => null,
        'version' => null,
        'listInInterface' => null,
        'createdDate' => 'date-time',
        'lastModifiedDate' => 'date-time'
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'id' => false,
        'isActive' => false,
        'appId' => false,
        'appName' => false,
        'algo' => false,
        'mapping' => false,
        'key' => true,
        'tokenQueryParameterName' => false,
        'clockSkew' => false,
        'loginUrl' => false,
        'issuer' => false,
        'subject' => false,
        'audience' => false,
        'expirationTimeDifference' => false,
        'useAuthorizationHeader' => false,
        'notBefore' => false,
        'expiration' => false,
        'jWKSUrl' => true,
        'updateEmailProfile' => false,
        'raasUpdateFields' => false,
        'domain' => true,
        'enableAutoLookUp' => true,
        'version' => true,
        'listInInterface' => false,
        'createdDate' => false,
        'lastModifiedDate' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'id' => 'Id',
        'isActive' => 'IsActive',
        'appId' => 'AppId',
        'appName' => 'AppName',
        'algo' => 'Algo',
        'mapping' => 'Mapping',
        'key' => 'Key',
        'tokenQueryParameterName' => 'TokenQueryParameterName',
        'clockSkew' => 'ClockSkew',
        'loginUrl' => 'LoginUrl',
        'issuer' => 'Issuer',
        'subject' => 'Subject',
        'audience' => 'Audience',
        'expirationTimeDifference' => 'ExpirationTimeDifference',
        'useAuthorizationHeader' => 'UseAuthorizationHeader',
        'notBefore' => 'NotBefore',
        'expiration' => 'Expiration',
        'jWKSUrl' => 'JWKSUrl',
        'updateEmailProfile' => 'UpdateEmailProfile',
        'raasUpdateFields' => 'RaasUpdateFields',
        'domain' => 'Domain',
        'enableAutoLookUp' => 'EnableAutoLookUp',
        'version' => 'Version',
        'listInInterface' => 'ListInInterface',
        'createdDate' => 'CreatedDate',
        'lastModifiedDate' => 'LastModifiedDate'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'id' => 'setId',
        'isActive' => 'setIsActive',
        'appId' => 'setAppId',
        'appName' => 'setAppName',
        'algo' => 'setAlgo',
        'mapping' => 'setMapping',
        'key' => 'setKey',
        'tokenQueryParameterName' => 'setTokenQueryParameterName',
        'clockSkew' => 'setClockSkew',
        'loginUrl' => 'setLoginUrl',
        'issuer' => 'setIssuer',
        'subject' => 'setSubject',
        'audience' => 'setAudience',
        'expirationTimeDifference' => 'setExpirationTimeDifference',
        'useAuthorizationHeader' => 'setUseAuthorizationHeader',
        'notBefore' => 'setNotBefore',
        'expiration' => 'setExpiration',
        'jWKSUrl' => 'setJWKSUrl',
        'updateEmailProfile' => 'setUpdateEmailProfile',
        'raasUpdateFields' => 'setRaasUpdateFields',
        'domain' => 'setDomain',
        'enableAutoLookUp' => 'setEnableAutoLookUp',
        'version' => 'setVersion',
        'listInInterface' => 'setListInInterface',
        'createdDate' => 'setCreatedDate',
        'lastModifiedDate' => 'setLastModifiedDate'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'id' => 'getId',
        'isActive' => 'getIsActive',
        'appId' => 'getAppId',
        'appName' => 'getAppName',
        'algo' => 'getAlgo',
        'mapping' => 'getMapping',
        'key' => 'getKey',
        'tokenQueryParameterName' => 'getTokenQueryParameterName',
        'clockSkew' => 'getClockSkew',
        'loginUrl' => 'getLoginUrl',
        'issuer' => 'getIssuer',
        'subject' => 'getSubject',
        'audience' => 'getAudience',
        'expirationTimeDifference' => 'getExpirationTimeDifference',
        'useAuthorizationHeader' => 'getUseAuthorizationHeader',
        'notBefore' => 'getNotBefore',
        'expiration' => 'getExpiration',
        'jWKSUrl' => 'getJWKSUrl',
        'updateEmailProfile' => 'getUpdateEmailProfile',
        'raasUpdateFields' => 'getRaasUpdateFields',
        'domain' => 'getDomain',
        'enableAutoLookUp' => 'getEnableAutoLookUp',
        'version' => 'getVersion',
        'listInInterface' => 'getListInInterface',
        'createdDate' => 'getCreatedDate',
        'lastModifiedDate' => 'getLastModifiedDate'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->setIfExists('id', $data ?? [], null);
        $this->setIfExists('isActive', $data ?? [], null);
        $this->setIfExists('appId', $data ?? [], null);
        $this->setIfExists('appName', $data ?? [], null);
        $this->setIfExists('algo', $data ?? [], null);
        $this->setIfExists('mapping', $data ?? [], null);
        $this->setIfExists('key', $data ?? [], null);
        $this->setIfExists('tokenQueryParameterName', $data ?? [], null);
        $this->setIfExists('clockSkew', $data ?? [], null);
        $this->setIfExists('loginUrl', $data ?? [], null);
        $this->setIfExists('issuer', $data ?? [], null);
        $this->setIfExists('subject', $data ?? [], null);
        $this->setIfExists('audience', $data ?? [], null);
        $this->setIfExists('expirationTimeDifference', $data ?? [], null);
        $this->setIfExists('useAuthorizationHeader', $data ?? [], null);
        $this->setIfExists('notBefore', $data ?? [], null);
        $this->setIfExists('expiration', $data ?? [], null);
        $this->setIfExists('jWKSUrl', $data ?? [], null);
        $this->setIfExists('updateEmailProfile', $data ?? [], null);
        $this->setIfExists('raasUpdateFields', $data ?? [], null);
        $this->setIfExists('domain', $data ?? [], null);
        $this->setIfExists('enableAutoLookUp', $data ?? [], null);
        $this->setIfExists('version', $data ?? [], null);
        $this->setIfExists('listInInterface', $data ?? [], null);
        $this->setIfExists('createdDate', $data ?? [], null);
        $this->setIfExists('lastModifiedDate', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets id
     *
     * @return string|null
     */
    public function getId()
    {
        return $this->container['id'];
    }

    /**
     * Sets id
     *
     * @param string|null $id id
     *
     * @return self
     */
    public function setId($id)
    {
        if (is_null($id)) {
            throw new \InvalidArgumentException('non-nullable id cannot be null');
        }
        $this->container['id'] = $id;

        return $this;
    }

    /**
     * Gets isActive
     *
     * @return bool|null
     */
    public function getIsActive()
    {
        return $this->container['isActive'];
    }

    /**
     * Sets isActive
     *
     * @param bool|null $isActive isActive
     *
     * @return self
     */
    public function setIsActive($isActive)
    {
        if (is_null($isActive)) {
            throw new \InvalidArgumentException('non-nullable isActive cannot be null');
        }
        $this->container['isActive'] = $isActive;

        return $this;
    }

    /**
     * Gets appId
     *
     * @return int|null
     */
    public function getAppId()
    {
        return $this->container['appId'];
    }

    /**
     * Sets appId
     *
     * @param int|null $appId appId
     *
     * @return self
     */
    public function setAppId($appId)
    {
        if (is_null($appId)) {
            throw new \InvalidArgumentException('non-nullable appId cannot be null');
        }
        $this->container['appId'] = $appId;

        return $this;
    }

    /**
     * Gets appName
     *
     * @return string|null
     */
    public function getAppName()
    {
        return $this->container['appName'];
    }

    /**
     * Sets appName
     *
     * @param string|null $appName appName
     *
     * @return self
     */
    public function setAppName($appName)
    {
        if (is_null($appName)) {
            throw new \InvalidArgumentException('non-nullable appName cannot be null');
        }
        $this->container['appName'] = $appName;

        return $this;
    }

    /**
     * Gets algo
     *
     * @return string|null
     */
    public function getAlgo()
    {
        return $this->container['algo'];
    }

    /**
     * Sets algo
     *
     * @param string|null $algo algo
     *
     * @return self
     */
    public function setAlgo($algo)
    {
        if (is_null($algo)) {
            throw new \InvalidArgumentException('non-nullable algo cannot be null');
        }
        $this->container['algo'] = $algo;

        return $this;
    }

    /**
     * Gets mapping
     *
     * @return array<string,string>|null
     */
    public function getMapping()
    {
        return $this->container['mapping'];
    }

    /**
     * Sets mapping
     *
     * @param array<string,string>|null $mapping mapping
     *
     * @return self
     */
    public function setMapping($mapping)
    {
        if (is_null($mapping)) {
            throw new \InvalidArgumentException('non-nullable mapping cannot be null');
        }
        $this->container['mapping'] = $mapping;

        return $this;
    }

    /**
     * Gets key
     *
     * @return string|null
     */
    public function getKey()
    {
        return $this->container['key'];
    }

    /**
     * Sets key
     *
     * @param string|null $key key
     *
     * @return self
     */
    public function setKey($key)
    {
        if (is_null($key)) {
            array_push($this->openAPINullablesSetToNull, 'key');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('key', $nullablesSetToNull, true);
            if ($index !== false) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['key'] = $key;

        return $this;
    }

    /**
     * Gets tokenQueryParameterName
     *
     * @return string|null
     */
    public function getTokenQueryParameterName()
    {
        return $this->container['tokenQueryParameterName'];
    }

    /**
     * Sets tokenQueryParameterName
     *
     * @param string|null $tokenQueryParameterName tokenQueryParameterName
     *
     * @return self
     */
    public function setTokenQueryParameterName($tokenQueryParameterName)
    {
        if (is_null($tokenQueryParameterName)) {
            throw new \InvalidArgumentException('non-nullable tokenQueryParameterName cannot be null');
        }
        $this->container['tokenQueryParameterName'] = $tokenQueryParameterName;

        return $this;
    }

    /**
     * Gets clockSkew
     *
     * @return int|null
     */
    public function getClockSkew()
    {
        return $this->container['clockSkew'];
    }

    /**
     * Sets clockSkew
     *
     * @param int|null $clockSkew clockSkew
     *
     * @return self
     */
    public function setClockSkew($clockSkew)
    {
        if (is_null($clockSkew)) {
            throw new \InvalidArgumentException('non-nullable clockSkew cannot be null');
        }
        $this->container['clockSkew'] = $clockSkew;

        return $this;
    }

    /**
     * Gets loginUrl
     *
     * @return string|null
     */
    public function getLoginUrl()
    {
        return $this->container['loginUrl'];
    }

    /**
     * Sets loginUrl
     *
     * @param string|null $loginUrl loginUrl
     *
     * @return self
     */
    public function setLoginUrl($loginUrl)
    {
        if (is_null($loginUrl)) {
            throw new \InvalidArgumentException('non-nullable loginUrl cannot be null');
        }
        $this->container['loginUrl'] = $loginUrl;

        return $this;
    }

    /**
     * Gets issuer
     *
     * @return \LoginRadius\Sdk\Internal\OpenApi\Model\JwtIssuerValidation|null
     */
    public function getIssuer()
    {
        return $this->container['issuer'];
    }

    /**
     * Sets issuer
     *
     * @param \LoginRadius\Sdk\Internal\OpenApi\Model\JwtIssuerValidation|null $issuer issuer
     *
     * @return self
     */
    public function setIssuer($issuer)
    {
        if (is_null($issuer)) {
            throw new \InvalidArgumentException('non-nullable issuer cannot be null');
        }
        $this->container['issuer'] = $issuer;

        return $this;
    }

    /**
     * Gets subject
     *
     * @return \LoginRadius\Sdk\Internal\OpenApi\Model\JwtValidation|null
     */
    public function getSubject()
    {
        return $this->container['subject'];
    }

    /**
     * Sets subject
     *
     * @param \LoginRadius\Sdk\Internal\OpenApi\Model\JwtValidation|null $subject subject
     *
     * @return self
     */
    public function setSubject($subject)
    {
        if (is_null($subject)) {
            throw new \InvalidArgumentException('non-nullable subject cannot be null');
        }
        $this->container['subject'] = $subject;

        return $this;
    }

    /**
     * Gets audience
     *
     * @return \LoginRadius\Sdk\Internal\OpenApi\Model\JwtAudienceValidation|null
     */
    public function getAudience()
    {
        return $this->container['audience'];
    }

    /**
     * Sets audience
     *
     * @param \LoginRadius\Sdk\Internal\OpenApi\Model\JwtAudienceValidation|null $audience audience
     *
     * @return self
     */
    public function setAudience($audience)
    {
        if (is_null($audience)) {
            throw new \InvalidArgumentException('non-nullable audience cannot be null');
        }
        $this->container['audience'] = $audience;

        return $this;
    }

    /**
     * Gets expirationTimeDifference
     *
     * @return int|null
     */
    public function getExpirationTimeDifference()
    {
        return $this->container['expirationTimeDifference'];
    }

    /**
     * Sets expirationTimeDifference
     *
     * @param int|null $expirationTimeDifference expirationTimeDifference
     *
     * @return self
     */
    public function setExpirationTimeDifference($expirationTimeDifference)
    {
        if (is_null($expirationTimeDifference)) {
            throw new \InvalidArgumentException('non-nullable expirationTimeDifference cannot be null');
        }
        $this->container['expirationTimeDifference'] = $expirationTimeDifference;

        return $this;
    }

    /**
     * Gets useAuthorizationHeader
     *
     * @return bool|null
     */
    public function getUseAuthorizationHeader()
    {
        return $this->container['useAuthorizationHeader'];
    }

    /**
     * Sets useAuthorizationHeader
     *
     * @param bool|null $useAuthorizationHeader useAuthorizationHeader
     *
     * @return self
     */
    public function setUseAuthorizationHeader($useAuthorizationHeader)
    {
        if (is_null($useAuthorizationHeader)) {
            throw new \InvalidArgumentException('non-nullable useAuthorizationHeader cannot be null');
        }
        $this->container['useAuthorizationHeader'] = $useAuthorizationHeader;

        return $this;
    }

    /**
     * Gets notBefore
     *
     * @return \LoginRadius\Sdk\Internal\OpenApi\Model\JwtValidation|null
     */
    public function getNotBefore()
    {
        return $this->container['notBefore'];
    }

    /**
     * Sets notBefore
     *
     * @param \LoginRadius\Sdk\Internal\OpenApi\Model\JwtValidation|null $notBefore notBefore
     *
     * @return self
     */
    public function setNotBefore($notBefore)
    {
        if (is_null($notBefore)) {
            throw new \InvalidArgumentException('non-nullable notBefore cannot be null');
        }
        $this->container['notBefore'] = $notBefore;

        return $this;
    }

    /**
     * Gets expiration
     *
     * @return \LoginRadius\Sdk\Internal\OpenApi\Model\JwtValidation|null
     */
    public function getExpiration()
    {
        return $this->container['expiration'];
    }

    /**
     * Sets expiration
     *
     * @param \LoginRadius\Sdk\Internal\OpenApi\Model\JwtValidation|null $expiration expiration
     *
     * @return self
     */
    public function setExpiration($expiration)
    {
        if (is_null($expiration)) {
            throw new \InvalidArgumentException('non-nullable expiration cannot be null');
        }
        $this->container['expiration'] = $expiration;

        return $this;
    }

    /**
     * Gets jWKSUrl
     *
     * @return string|null
     */
    public function getJWKSUrl()
    {
        return $this->container['jWKSUrl'];
    }

    /**
     * Sets jWKSUrl
     *
     * @param string|null $jWKSUrl jWKSUrl
     *
     * @return self
     */
    public function setJWKSUrl($jWKSUrl)
    {
        if (is_null($jWKSUrl)) {
            array_push($this->openAPINullablesSetToNull, 'jWKSUrl');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('jWKSUrl', $nullablesSetToNull, true);
            if ($index !== false) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['jWKSUrl'] = $jWKSUrl;

        return $this;
    }

    /**
     * Gets updateEmailProfile
     *
     * @return bool|null
     */
    public function getUpdateEmailProfile()
    {
        return $this->container['updateEmailProfile'];
    }

    /**
     * Sets updateEmailProfile
     *
     * @param bool|null $updateEmailProfile updateEmailProfile
     *
     * @return self
     */
    public function setUpdateEmailProfile($updateEmailProfile)
    {
        if (is_null($updateEmailProfile)) {
            throw new \InvalidArgumentException('non-nullable updateEmailProfile cannot be null');
        }
        $this->container['updateEmailProfile'] = $updateEmailProfile;

        return $this;
    }

    /**
     * Gets raasUpdateFields
     *
     * @return string[]|null
     */
    public function getRaasUpdateFields()
    {
        return $this->container['raasUpdateFields'];
    }

    /**
     * Sets raasUpdateFields
     *
     * @param string[]|null $raasUpdateFields raasUpdateFields
     *
     * @return self
     */
    public function setRaasUpdateFields($raasUpdateFields)
    {
        if (is_null($raasUpdateFields)) {
            throw new \InvalidArgumentException('non-nullable raasUpdateFields cannot be null');
        }
        $this->container['raasUpdateFields'] = $raasUpdateFields;

        return $this;
    }

    /**
     * Gets domain
     *
     * @return string|null
     */
    public function getDomain()
    {
        return $this->container['domain'];
    }

    /**
     * Sets domain
     *
     * @param string|null $domain domain
     *
     * @return self
     */
    public function setDomain($domain)
    {
        if (is_null($domain)) {
            array_push($this->openAPINullablesSetToNull, 'domain');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('domain', $nullablesSetToNull, true);
            if ($index !== false) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['domain'] = $domain;

        return $this;
    }

    /**
     * Gets enableAutoLookUp
     *
     * @return bool|null
     */
    public function getEnableAutoLookUp()
    {
        return $this->container['enableAutoLookUp'];
    }

    /**
     * Sets enableAutoLookUp
     *
     * @param bool|null $enableAutoLookUp enableAutoLookUp
     *
     * @return self
     */
    public function setEnableAutoLookUp($enableAutoLookUp)
    {
        if (is_null($enableAutoLookUp)) {
            array_push($this->openAPINullablesSetToNull, 'enableAutoLookUp');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('enableAutoLookUp', $nullablesSetToNull, true);
            if ($index !== false) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['enableAutoLookUp'] = $enableAutoLookUp;

        return $this;
    }

    /**
     * Gets version
     *
     * @return string|null
     */
    public function getVersion()
    {
        return $this->container['version'];
    }

    /**
     * Sets version
     *
     * @param string|null $version version
     *
     * @return self
     */
    public function setVersion($version)
    {
        if (is_null($version)) {
            array_push($this->openAPINullablesSetToNull, 'version');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('version', $nullablesSetToNull, true);
            if ($index !== false) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['version'] = $version;

        return $this;
    }

    /**
     * Gets listInInterface
     *
     * @return bool|null
     */
    public function getListInInterface()
    {
        return $this->container['listInInterface'];
    }

    /**
     * Sets listInInterface
     *
     * @param bool|null $listInInterface listInInterface
     *
     * @return self
     */
    public function setListInInterface($listInInterface)
    {
        if (is_null($listInInterface)) {
            throw new \InvalidArgumentException('non-nullable listInInterface cannot be null');
        }
        $this->container['listInInterface'] = $listInInterface;

        return $this;
    }

    /**
     * Gets createdDate
     *
     * @return \DateTime|null
     */
    public function getCreatedDate()
    {
        return $this->container['createdDate'];
    }

    /**
     * Sets createdDate
     *
     * @param \DateTime|null $createdDate createdDate
     *
     * @return self
     */
    public function setCreatedDate($createdDate)
    {
        if (is_null($createdDate)) {
            throw new \InvalidArgumentException('non-nullable createdDate cannot be null');
        }
        $this->container['createdDate'] = $createdDate;

        return $this;
    }

    /**
     * Gets lastModifiedDate
     *
     * @return \DateTime|null
     */
    public function getLastModifiedDate()
    {
        return $this->container['lastModifiedDate'];
    }

    /**
     * Sets lastModifiedDate
     *
     * @param \DateTime|null $lastModifiedDate lastModifiedDate
     *
     * @return self
     */
    public function setLastModifiedDate($lastModifiedDate)
    {
        if (is_null($lastModifiedDate)) {
            throw new \InvalidArgumentException('non-nullable lastModifiedDate cannot be null');
        }
        $this->container['lastModifiedDate'] = $lastModifiedDate;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
        return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


