<?php

/**
 * LoginByPhone
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  LoginRadius\Sdk\Internal\OpenApi
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * LoginRadius API
 *
 * This is a LoginRadius API server. Which you can use to authenticate and manage the user.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@loginradius.com
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.10.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace LoginRadius\Sdk\Internal\OpenApi\Model;

use \ArrayAccess;
use \LoginRadius\Sdk\Internal\OpenApi\ObjectSerializer;

/**
 * LoginByPhone Class Doc Comment
 *
 * @category Class
 * @package  LoginRadius\Sdk\Internal\OpenApi
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class LoginByPhone implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'LoginByPhone';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'gRecaptchaResponse' => 'string',
        'qqCaptchaTicket' => 'string',
        'qqCaptchaRandstr' => 'string',
        'hCaptchaResponse' => 'string',
        'phone' => 'string',
        'password' => 'string',
        'securityAnswer' => 'string'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'gRecaptchaResponse' => null,
        'qqCaptchaTicket' => null,
        'qqCaptchaRandstr' => null,
        'hCaptchaResponse' => null,
        'phone' => null,
        'password' => 'password',
        'securityAnswer' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'gRecaptchaResponse' => true,
        'qqCaptchaTicket' => true,
        'qqCaptchaRandstr' => true,
        'hCaptchaResponse' => true,
        'phone' => false,
        'password' => false,
        'securityAnswer' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'gRecaptchaResponse' => 'g-recaptcha-response',
        'qqCaptchaTicket' => 'qq_captcha_ticket',
        'qqCaptchaRandstr' => 'qq_captcha_randstr',
        'hCaptchaResponse' => 'h-captcha-response',
        'phone' => 'phone',
        'password' => 'password',
        'securityAnswer' => 'securityAnswer'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'gRecaptchaResponse' => 'setGRecaptchaResponse',
        'qqCaptchaTicket' => 'setQqCaptchaTicket',
        'qqCaptchaRandstr' => 'setQqCaptchaRandstr',
        'hCaptchaResponse' => 'setHCaptchaResponse',
        'phone' => 'setPhone',
        'password' => 'setPassword',
        'securityAnswer' => 'setSecurityAnswer'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'gRecaptchaResponse' => 'getGRecaptchaResponse',
        'qqCaptchaTicket' => 'getQqCaptchaTicket',
        'qqCaptchaRandstr' => 'getQqCaptchaRandstr',
        'hCaptchaResponse' => 'getHCaptchaResponse',
        'phone' => 'getPhone',
        'password' => 'getPassword',
        'securityAnswer' => 'getSecurityAnswer'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->setIfExists('gRecaptchaResponse', $data ?? [], null);
        $this->setIfExists('qqCaptchaTicket', $data ?? [], null);
        $this->setIfExists('qqCaptchaRandstr', $data ?? [], null);
        $this->setIfExists('hCaptchaResponse', $data ?? [], null);
        $this->setIfExists('phone', $data ?? [], null);
        $this->setIfExists('password', $data ?? [], null);
        $this->setIfExists('securityAnswer', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['phone'] === null) {
            $invalidProperties[] = "'phone' can't be null";
        }
        if ($this->container['password'] === null) {
            $invalidProperties[] = "'password' can't be null";
        }
        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets gRecaptchaResponse
     *
     * @return string|null
     */
    public function getGRecaptchaResponse()
    {
        return $this->container['gRecaptchaResponse'];
    }

    /**
     * Sets gRecaptchaResponse
     *
     * @param string|null $gRecaptchaResponse The Google reCAPTCHA response which is sent to the server for verification.
     *
     * @return self
     */
    public function setGRecaptchaResponse($gRecaptchaResponse)
    {
        if (is_null($gRecaptchaResponse)) {
            array_push($this->openAPINullablesSetToNull, 'gRecaptchaResponse');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('gRecaptchaResponse', $nullablesSetToNull, true);
            if ($index !== false) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['gRecaptchaResponse'] = $gRecaptchaResponse;

        return $this;
    }

    /**
     * Gets qqCaptchaTicket
     *
     * @return string|null
     */
    public function getQqCaptchaTicket()
    {
        return $this->container['qqCaptchaTicket'];
    }

    /**
     * Sets qqCaptchaTicket
     *
     * @param string|null $qqCaptchaTicket The QQ Captcha ticket which is sent to the server for verification.
     *
     * @return self
     */
    public function setQqCaptchaTicket($qqCaptchaTicket)
    {
        if (is_null($qqCaptchaTicket)) {
            array_push($this->openAPINullablesSetToNull, 'qqCaptchaTicket');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('qqCaptchaTicket', $nullablesSetToNull, true);
            if ($index !== false) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['qqCaptchaTicket'] = $qqCaptchaTicket;

        return $this;
    }

    /**
     * Gets qqCaptchaRandstr
     *
     * @return string|null
     */
    public function getQqCaptchaRandstr()
    {
        return $this->container['qqCaptchaRandstr'];
    }

    /**
     * Sets qqCaptchaRandstr
     *
     * @param string|null $qqCaptchaRandstr The QQ Captcha random string which is sent to the server for verification.
     *
     * @return self
     */
    public function setQqCaptchaRandstr($qqCaptchaRandstr)
    {
        if (is_null($qqCaptchaRandstr)) {
            array_push($this->openAPINullablesSetToNull, 'qqCaptchaRandstr');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('qqCaptchaRandstr', $nullablesSetToNull, true);
            if ($index !== false) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['qqCaptchaRandstr'] = $qqCaptchaRandstr;

        return $this;
    }

    /**
     * Gets hCaptchaResponse
     *
     * @return string|null
     */
    public function getHCaptchaResponse()
    {
        return $this->container['hCaptchaResponse'];
    }

    /**
     * Sets hCaptchaResponse
     *
     * @param string|null $hCaptchaResponse The hCaptcha response which is sent to the server for verification.
     *
     * @return self
     */
    public function setHCaptchaResponse($hCaptchaResponse)
    {
        if (is_null($hCaptchaResponse)) {
            array_push($this->openAPINullablesSetToNull, 'hCaptchaResponse');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('hCaptchaResponse', $nullablesSetToNull, true);
            if ($index !== false) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['hCaptchaResponse'] = $hCaptchaResponse;

        return $this;
    }

    /**
     * Gets phone
     *
     * @return string
     */
    public function getPhone()
    {
        return $this->container['phone'];
    }

    /**
     * Sets phone
     *
     * @param string $phone The Phone number of the User
     *
     * @return self
     */
    public function setPhone($phone)
    {
        if (is_null($phone)) {
            throw new \InvalidArgumentException('non-nullable phone cannot be null');
        }
        $this->container['phone'] = $phone;

        return $this;
    }

    /**
     * Gets password
     *
     * @return string
     */
    public function getPassword()
    {
        return $this->container['password'];
    }

    /**
     * Sets password
     *
     * @param string $password The Password of the User
     *
     * @return self
     */
    public function setPassword($password)
    {
        if (is_null($password)) {
            throw new \InvalidArgumentException('non-nullable password cannot be null');
        }
        $this->container['password'] = $password;

        return $this;
    }

    /**
     * Gets securityAnswer
     *
     * @return string|null
     */
    public function getSecurityAnswer()
    {
        return $this->container['securityAnswer'];
    }

    /**
     * Sets securityAnswer
     *
     * @param string|null $securityAnswer The security answer which is set for the User, this will be used when the User is blocked for the security question.
     *
     * @return self
     */
    public function setSecurityAnswer($securityAnswer)
    {
        if (is_null($securityAnswer)) {
            throw new \InvalidArgumentException('non-nullable securityAnswer cannot be null');
        }
        $this->container['securityAnswer'] = $securityAnswer;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
        return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


