<?php

/**
 * OIDCDiscoveryResponse
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  LoginRadius\Sdk\Internal\OpenApi
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * LoginRadius API
 *
 * This is a LoginRadius API server. Which you can use to authenticate and manage the user.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@loginradius.com
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.10.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace LoginRadius\Sdk\Internal\OpenApi\Model;

use \ArrayAccess;
use \LoginRadius\Sdk\Internal\OpenApi\ObjectSerializer;

/**
 * OIDCDiscoveryResponse Class Doc Comment
 *
 * @category Class
 * @description OIDC Discovery Config Response
 * @package  LoginRadius\Sdk\Internal\OpenApi
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class OIDCDiscoveryResponse implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'OIDCDiscoveryResponse';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'acrValuesSupported' => 'string[]',
        'authorizationEndpoint' => 'string',
        'backchannelLogoutSessionSupported' => 'bool',
        'backchannelLogoutSupported' => 'bool',
        'claimsSupported' => 'string[]',
        'codeChallengeMethodsSupported' => 'string[]',
        'endSessionEndpoint' => 'string',
        'grantTypesSupported' => 'string[]',
        'idTokenSigningAlgValuesSupported' => 'string[]',
        'issuer' => 'string',
        'jwksUri' => 'string',
        'requestParameterSupported' => 'bool',
        'responseModesSupported' => 'string[]',
        'responseTypesSupported' => 'string[]',
        'revocationEndpoint' => 'string',
        'introspectionEndpoint' => 'string',
        'revocationEndpointAuthMethodsSupported' => 'string[]',
        'scopesSupported' => 'string[]',
        'subjectTypesSupported' => 'string[]',
        'tokenEndpoint' => 'string',
        'tokenEndpointAuthMethodsSupported' => 'string[]',
        'userinfoEndpoint' => 'string'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'acrValuesSupported' => null,
        'authorizationEndpoint' => null,
        'backchannelLogoutSessionSupported' => null,
        'backchannelLogoutSupported' => null,
        'claimsSupported' => null,
        'codeChallengeMethodsSupported' => null,
        'endSessionEndpoint' => null,
        'grantTypesSupported' => null,
        'idTokenSigningAlgValuesSupported' => null,
        'issuer' => null,
        'jwksUri' => null,
        'requestParameterSupported' => null,
        'responseModesSupported' => null,
        'responseTypesSupported' => null,
        'revocationEndpoint' => null,
        'introspectionEndpoint' => null,
        'revocationEndpointAuthMethodsSupported' => null,
        'scopesSupported' => null,
        'subjectTypesSupported' => null,
        'tokenEndpoint' => null,
        'tokenEndpointAuthMethodsSupported' => null,
        'userinfoEndpoint' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'acrValuesSupported' => false,
        'authorizationEndpoint' => false,
        'backchannelLogoutSessionSupported' => false,
        'backchannelLogoutSupported' => false,
        'claimsSupported' => false,
        'codeChallengeMethodsSupported' => false,
        'endSessionEndpoint' => false,
        'grantTypesSupported' => false,
        'idTokenSigningAlgValuesSupported' => false,
        'issuer' => false,
        'jwksUri' => false,
        'requestParameterSupported' => false,
        'responseModesSupported' => false,
        'responseTypesSupported' => false,
        'revocationEndpoint' => false,
        'introspectionEndpoint' => false,
        'revocationEndpointAuthMethodsSupported' => false,
        'scopesSupported' => false,
        'subjectTypesSupported' => false,
        'tokenEndpoint' => false,
        'tokenEndpointAuthMethodsSupported' => false,
        'userinfoEndpoint' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'acrValuesSupported' => 'acr_values_supported',
        'authorizationEndpoint' => 'authorization_endpoint',
        'backchannelLogoutSessionSupported' => 'backchannel_logout_session_supported',
        'backchannelLogoutSupported' => 'backchannel_logout_supported',
        'claimsSupported' => 'claims_supported',
        'codeChallengeMethodsSupported' => 'code_challenge_methods_supported',
        'endSessionEndpoint' => 'end_session_endpoint',
        'grantTypesSupported' => 'grant_types_supported',
        'idTokenSigningAlgValuesSupported' => 'id_token_signing_alg_values_supported',
        'issuer' => 'issuer',
        'jwksUri' => 'jwks_uri',
        'requestParameterSupported' => 'request_parameter_supported',
        'responseModesSupported' => 'response_modes_supported',
        'responseTypesSupported' => 'response_types_supported',
        'revocationEndpoint' => 'revocation_endpoint',
        'introspectionEndpoint' => 'introspection_endpoint',
        'revocationEndpointAuthMethodsSupported' => 'revocation_endpoint_auth_methods_supported',
        'scopesSupported' => 'scopes_supported',
        'subjectTypesSupported' => 'subject_types_supported',
        'tokenEndpoint' => 'token_endpoint',
        'tokenEndpointAuthMethodsSupported' => 'token_endpoint_auth_methods_supported',
        'userinfoEndpoint' => 'userinfo_endpoint'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'acrValuesSupported' => 'setAcrValuesSupported',
        'authorizationEndpoint' => 'setAuthorizationEndpoint',
        'backchannelLogoutSessionSupported' => 'setBackchannelLogoutSessionSupported',
        'backchannelLogoutSupported' => 'setBackchannelLogoutSupported',
        'claimsSupported' => 'setClaimsSupported',
        'codeChallengeMethodsSupported' => 'setCodeChallengeMethodsSupported',
        'endSessionEndpoint' => 'setEndSessionEndpoint',
        'grantTypesSupported' => 'setGrantTypesSupported',
        'idTokenSigningAlgValuesSupported' => 'setIdTokenSigningAlgValuesSupported',
        'issuer' => 'setIssuer',
        'jwksUri' => 'setJwksUri',
        'requestParameterSupported' => 'setRequestParameterSupported',
        'responseModesSupported' => 'setResponseModesSupported',
        'responseTypesSupported' => 'setResponseTypesSupported',
        'revocationEndpoint' => 'setRevocationEndpoint',
        'introspectionEndpoint' => 'setIntrospectionEndpoint',
        'revocationEndpointAuthMethodsSupported' => 'setRevocationEndpointAuthMethodsSupported',
        'scopesSupported' => 'setScopesSupported',
        'subjectTypesSupported' => 'setSubjectTypesSupported',
        'tokenEndpoint' => 'setTokenEndpoint',
        'tokenEndpointAuthMethodsSupported' => 'setTokenEndpointAuthMethodsSupported',
        'userinfoEndpoint' => 'setUserinfoEndpoint'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'acrValuesSupported' => 'getAcrValuesSupported',
        'authorizationEndpoint' => 'getAuthorizationEndpoint',
        'backchannelLogoutSessionSupported' => 'getBackchannelLogoutSessionSupported',
        'backchannelLogoutSupported' => 'getBackchannelLogoutSupported',
        'claimsSupported' => 'getClaimsSupported',
        'codeChallengeMethodsSupported' => 'getCodeChallengeMethodsSupported',
        'endSessionEndpoint' => 'getEndSessionEndpoint',
        'grantTypesSupported' => 'getGrantTypesSupported',
        'idTokenSigningAlgValuesSupported' => 'getIdTokenSigningAlgValuesSupported',
        'issuer' => 'getIssuer',
        'jwksUri' => 'getJwksUri',
        'requestParameterSupported' => 'getRequestParameterSupported',
        'responseModesSupported' => 'getResponseModesSupported',
        'responseTypesSupported' => 'getResponseTypesSupported',
        'revocationEndpoint' => 'getRevocationEndpoint',
        'introspectionEndpoint' => 'getIntrospectionEndpoint',
        'revocationEndpointAuthMethodsSupported' => 'getRevocationEndpointAuthMethodsSupported',
        'scopesSupported' => 'getScopesSupported',
        'subjectTypesSupported' => 'getSubjectTypesSupported',
        'tokenEndpoint' => 'getTokenEndpoint',
        'tokenEndpointAuthMethodsSupported' => 'getTokenEndpointAuthMethodsSupported',
        'userinfoEndpoint' => 'getUserinfoEndpoint'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->setIfExists('acrValuesSupported', $data ?? [], null);
        $this->setIfExists('authorizationEndpoint', $data ?? [], null);
        $this->setIfExists('backchannelLogoutSessionSupported', $data ?? [], null);
        $this->setIfExists('backchannelLogoutSupported', $data ?? [], null);
        $this->setIfExists('claimsSupported', $data ?? [], null);
        $this->setIfExists('codeChallengeMethodsSupported', $data ?? [], null);
        $this->setIfExists('endSessionEndpoint', $data ?? [], null);
        $this->setIfExists('grantTypesSupported', $data ?? [], null);
        $this->setIfExists('idTokenSigningAlgValuesSupported', $data ?? [], null);
        $this->setIfExists('issuer', $data ?? [], null);
        $this->setIfExists('jwksUri', $data ?? [], null);
        $this->setIfExists('requestParameterSupported', $data ?? [], null);
        $this->setIfExists('responseModesSupported', $data ?? [], null);
        $this->setIfExists('responseTypesSupported', $data ?? [], null);
        $this->setIfExists('revocationEndpoint', $data ?? [], null);
        $this->setIfExists('introspectionEndpoint', $data ?? [], null);
        $this->setIfExists('revocationEndpointAuthMethodsSupported', $data ?? [], null);
        $this->setIfExists('scopesSupported', $data ?? [], null);
        $this->setIfExists('subjectTypesSupported', $data ?? [], null);
        $this->setIfExists('tokenEndpoint', $data ?? [], null);
        $this->setIfExists('tokenEndpointAuthMethodsSupported', $data ?? [], null);
        $this->setIfExists('userinfoEndpoint', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets acrValuesSupported
     *
     * @return string[]|null
     */
    public function getAcrValuesSupported()
    {
        return $this->container['acrValuesSupported'];
    }

    /**
     * Sets acrValuesSupported
     *
     * @param string[]|null $acrValuesSupported acrValuesSupported
     *
     * @return self
     */
    public function setAcrValuesSupported($acrValuesSupported)
    {
        if (is_null($acrValuesSupported)) {
            throw new \InvalidArgumentException('non-nullable acrValuesSupported cannot be null');
        }
        $this->container['acrValuesSupported'] = $acrValuesSupported;

        return $this;
    }

    /**
     * Gets authorizationEndpoint
     *
     * @return string|null
     */
    public function getAuthorizationEndpoint()
    {
        return $this->container['authorizationEndpoint'];
    }

    /**
     * Sets authorizationEndpoint
     *
     * @param string|null $authorizationEndpoint authorizationEndpoint
     *
     * @return self
     */
    public function setAuthorizationEndpoint($authorizationEndpoint)
    {
        if (is_null($authorizationEndpoint)) {
            throw new \InvalidArgumentException('non-nullable authorizationEndpoint cannot be null');
        }
        $this->container['authorizationEndpoint'] = $authorizationEndpoint;

        return $this;
    }

    /**
     * Gets backchannelLogoutSessionSupported
     *
     * @return bool|null
     */
    public function getBackchannelLogoutSessionSupported()
    {
        return $this->container['backchannelLogoutSessionSupported'];
    }

    /**
     * Sets backchannelLogoutSessionSupported
     *
     * @param bool|null $backchannelLogoutSessionSupported backchannelLogoutSessionSupported
     *
     * @return self
     */
    public function setBackchannelLogoutSessionSupported($backchannelLogoutSessionSupported)
    {
        if (is_null($backchannelLogoutSessionSupported)) {
            throw new \InvalidArgumentException('non-nullable backchannelLogoutSessionSupported cannot be null');
        }
        $this->container['backchannelLogoutSessionSupported'] = $backchannelLogoutSessionSupported;

        return $this;
    }

    /**
     * Gets backchannelLogoutSupported
     *
     * @return bool|null
     */
    public function getBackchannelLogoutSupported()
    {
        return $this->container['backchannelLogoutSupported'];
    }

    /**
     * Sets backchannelLogoutSupported
     *
     * @param bool|null $backchannelLogoutSupported backchannelLogoutSupported
     *
     * @return self
     */
    public function setBackchannelLogoutSupported($backchannelLogoutSupported)
    {
        if (is_null($backchannelLogoutSupported)) {
            throw new \InvalidArgumentException('non-nullable backchannelLogoutSupported cannot be null');
        }
        $this->container['backchannelLogoutSupported'] = $backchannelLogoutSupported;

        return $this;
    }

    /**
     * Gets claimsSupported
     *
     * @return string[]|null
     */
    public function getClaimsSupported()
    {
        return $this->container['claimsSupported'];
    }

    /**
     * Sets claimsSupported
     *
     * @param string[]|null $claimsSupported claimsSupported
     *
     * @return self
     */
    public function setClaimsSupported($claimsSupported)
    {
        if (is_null($claimsSupported)) {
            throw new \InvalidArgumentException('non-nullable claimsSupported cannot be null');
        }
        $this->container['claimsSupported'] = $claimsSupported;

        return $this;
    }

    /**
     * Gets codeChallengeMethodsSupported
     *
     * @return string[]|null
     */
    public function getCodeChallengeMethodsSupported()
    {
        return $this->container['codeChallengeMethodsSupported'];
    }

    /**
     * Sets codeChallengeMethodsSupported
     *
     * @param string[]|null $codeChallengeMethodsSupported codeChallengeMethodsSupported
     *
     * @return self
     */
    public function setCodeChallengeMethodsSupported($codeChallengeMethodsSupported)
    {
        if (is_null($codeChallengeMethodsSupported)) {
            throw new \InvalidArgumentException('non-nullable codeChallengeMethodsSupported cannot be null');
        }
        $this->container['codeChallengeMethodsSupported'] = $codeChallengeMethodsSupported;

        return $this;
    }

    /**
     * Gets endSessionEndpoint
     *
     * @return string|null
     */
    public function getEndSessionEndpoint()
    {
        return $this->container['endSessionEndpoint'];
    }

    /**
     * Sets endSessionEndpoint
     *
     * @param string|null $endSessionEndpoint endSessionEndpoint
     *
     * @return self
     */
    public function setEndSessionEndpoint($endSessionEndpoint)
    {
        if (is_null($endSessionEndpoint)) {
            throw new \InvalidArgumentException('non-nullable endSessionEndpoint cannot be null');
        }
        $this->container['endSessionEndpoint'] = $endSessionEndpoint;

        return $this;
    }

    /**
     * Gets grantTypesSupported
     *
     * @return string[]|null
     */
    public function getGrantTypesSupported()
    {
        return $this->container['grantTypesSupported'];
    }

    /**
     * Sets grantTypesSupported
     *
     * @param string[]|null $grantTypesSupported grantTypesSupported
     *
     * @return self
     */
    public function setGrantTypesSupported($grantTypesSupported)
    {
        if (is_null($grantTypesSupported)) {
            throw new \InvalidArgumentException('non-nullable grantTypesSupported cannot be null');
        }
        $this->container['grantTypesSupported'] = $grantTypesSupported;

        return $this;
    }

    /**
     * Gets idTokenSigningAlgValuesSupported
     *
     * @return string[]|null
     */
    public function getIdTokenSigningAlgValuesSupported()
    {
        return $this->container['idTokenSigningAlgValuesSupported'];
    }

    /**
     * Sets idTokenSigningAlgValuesSupported
     *
     * @param string[]|null $idTokenSigningAlgValuesSupported idTokenSigningAlgValuesSupported
     *
     * @return self
     */
    public function setIdTokenSigningAlgValuesSupported($idTokenSigningAlgValuesSupported)
    {
        if (is_null($idTokenSigningAlgValuesSupported)) {
            throw new \InvalidArgumentException('non-nullable idTokenSigningAlgValuesSupported cannot be null');
        }
        $this->container['idTokenSigningAlgValuesSupported'] = $idTokenSigningAlgValuesSupported;

        return $this;
    }

    /**
     * Gets issuer
     *
     * @return string|null
     */
    public function getIssuer()
    {
        return $this->container['issuer'];
    }

    /**
     * Sets issuer
     *
     * @param string|null $issuer issuer
     *
     * @return self
     */
    public function setIssuer($issuer)
    {
        if (is_null($issuer)) {
            throw new \InvalidArgumentException('non-nullable issuer cannot be null');
        }
        $this->container['issuer'] = $issuer;

        return $this;
    }

    /**
     * Gets jwksUri
     *
     * @return string|null
     */
    public function getJwksUri()
    {
        return $this->container['jwksUri'];
    }

    /**
     * Sets jwksUri
     *
     * @param string|null $jwksUri jwksUri
     *
     * @return self
     */
    public function setJwksUri($jwksUri)
    {
        if (is_null($jwksUri)) {
            throw new \InvalidArgumentException('non-nullable jwksUri cannot be null');
        }
        $this->container['jwksUri'] = $jwksUri;

        return $this;
    }

    /**
     * Gets requestParameterSupported
     *
     * @return bool|null
     */
    public function getRequestParameterSupported()
    {
        return $this->container['requestParameterSupported'];
    }

    /**
     * Sets requestParameterSupported
     *
     * @param bool|null $requestParameterSupported requestParameterSupported
     *
     * @return self
     */
    public function setRequestParameterSupported($requestParameterSupported)
    {
        if (is_null($requestParameterSupported)) {
            throw new \InvalidArgumentException('non-nullable requestParameterSupported cannot be null');
        }
        $this->container['requestParameterSupported'] = $requestParameterSupported;

        return $this;
    }

    /**
     * Gets responseModesSupported
     *
     * @return string[]|null
     */
    public function getResponseModesSupported()
    {
        return $this->container['responseModesSupported'];
    }

    /**
     * Sets responseModesSupported
     *
     * @param string[]|null $responseModesSupported responseModesSupported
     *
     * @return self
     */
    public function setResponseModesSupported($responseModesSupported)
    {
        if (is_null($responseModesSupported)) {
            throw new \InvalidArgumentException('non-nullable responseModesSupported cannot be null');
        }
        $this->container['responseModesSupported'] = $responseModesSupported;

        return $this;
    }

    /**
     * Gets responseTypesSupported
     *
     * @return string[]|null
     */
    public function getResponseTypesSupported()
    {
        return $this->container['responseTypesSupported'];
    }

    /**
     * Sets responseTypesSupported
     *
     * @param string[]|null $responseTypesSupported responseTypesSupported
     *
     * @return self
     */
    public function setResponseTypesSupported($responseTypesSupported)
    {
        if (is_null($responseTypesSupported)) {
            throw new \InvalidArgumentException('non-nullable responseTypesSupported cannot be null');
        }
        $this->container['responseTypesSupported'] = $responseTypesSupported;

        return $this;
    }

    /**
     * Gets revocationEndpoint
     *
     * @return string|null
     */
    public function getRevocationEndpoint()
    {
        return $this->container['revocationEndpoint'];
    }

    /**
     * Sets revocationEndpoint
     *
     * @param string|null $revocationEndpoint revocationEndpoint
     *
     * @return self
     */
    public function setRevocationEndpoint($revocationEndpoint)
    {
        if (is_null($revocationEndpoint)) {
            throw new \InvalidArgumentException('non-nullable revocationEndpoint cannot be null');
        }
        $this->container['revocationEndpoint'] = $revocationEndpoint;

        return $this;
    }

    /**
     * Gets introspectionEndpoint
     *
     * @return string|null
     */
    public function getIntrospectionEndpoint()
    {
        return $this->container['introspectionEndpoint'];
    }

    /**
     * Sets introspectionEndpoint
     *
     * @param string|null $introspectionEndpoint OAuth 2.0 Token Introspection endpoint (RFC 7662)
     *
     * @return self
     */
    public function setIntrospectionEndpoint($introspectionEndpoint)
    {
        if (is_null($introspectionEndpoint)) {
            throw new \InvalidArgumentException('non-nullable introspectionEndpoint cannot be null');
        }
        $this->container['introspectionEndpoint'] = $introspectionEndpoint;

        return $this;
    }

    /**
     * Gets revocationEndpointAuthMethodsSupported
     *
     * @return string[]|null
     */
    public function getRevocationEndpointAuthMethodsSupported()
    {
        return $this->container['revocationEndpointAuthMethodsSupported'];
    }

    /**
     * Sets revocationEndpointAuthMethodsSupported
     *
     * @param string[]|null $revocationEndpointAuthMethodsSupported revocationEndpointAuthMethodsSupported
     *
     * @return self
     */
    public function setRevocationEndpointAuthMethodsSupported($revocationEndpointAuthMethodsSupported)
    {
        if (is_null($revocationEndpointAuthMethodsSupported)) {
            throw new \InvalidArgumentException('non-nullable revocationEndpointAuthMethodsSupported cannot be null');
        }
        $this->container['revocationEndpointAuthMethodsSupported'] = $revocationEndpointAuthMethodsSupported;

        return $this;
    }

    /**
     * Gets scopesSupported
     *
     * @return string[]|null
     */
    public function getScopesSupported()
    {
        return $this->container['scopesSupported'];
    }

    /**
     * Sets scopesSupported
     *
     * @param string[]|null $scopesSupported scopesSupported
     *
     * @return self
     */
    public function setScopesSupported($scopesSupported)
    {
        if (is_null($scopesSupported)) {
            throw new \InvalidArgumentException('non-nullable scopesSupported cannot be null');
        }
        $this->container['scopesSupported'] = $scopesSupported;

        return $this;
    }

    /**
     * Gets subjectTypesSupported
     *
     * @return string[]|null
     */
    public function getSubjectTypesSupported()
    {
        return $this->container['subjectTypesSupported'];
    }

    /**
     * Sets subjectTypesSupported
     *
     * @param string[]|null $subjectTypesSupported subjectTypesSupported
     *
     * @return self
     */
    public function setSubjectTypesSupported($subjectTypesSupported)
    {
        if (is_null($subjectTypesSupported)) {
            throw new \InvalidArgumentException('non-nullable subjectTypesSupported cannot be null');
        }
        $this->container['subjectTypesSupported'] = $subjectTypesSupported;

        return $this;
    }

    /**
     * Gets tokenEndpoint
     *
     * @return string|null
     */
    public function getTokenEndpoint()
    {
        return $this->container['tokenEndpoint'];
    }

    /**
     * Sets tokenEndpoint
     *
     * @param string|null $tokenEndpoint tokenEndpoint
     *
     * @return self
     */
    public function setTokenEndpoint($tokenEndpoint)
    {
        if (is_null($tokenEndpoint)) {
            throw new \InvalidArgumentException('non-nullable tokenEndpoint cannot be null');
        }
        $this->container['tokenEndpoint'] = $tokenEndpoint;

        return $this;
    }

    /**
     * Gets tokenEndpointAuthMethodsSupported
     *
     * @return string[]|null
     */
    public function getTokenEndpointAuthMethodsSupported()
    {
        return $this->container['tokenEndpointAuthMethodsSupported'];
    }

    /**
     * Sets tokenEndpointAuthMethodsSupported
     *
     * @param string[]|null $tokenEndpointAuthMethodsSupported tokenEndpointAuthMethodsSupported
     *
     * @return self
     */
    public function setTokenEndpointAuthMethodsSupported($tokenEndpointAuthMethodsSupported)
    {
        if (is_null($tokenEndpointAuthMethodsSupported)) {
            throw new \InvalidArgumentException('non-nullable tokenEndpointAuthMethodsSupported cannot be null');
        }
        $this->container['tokenEndpointAuthMethodsSupported'] = $tokenEndpointAuthMethodsSupported;

        return $this;
    }

    /**
     * Gets userinfoEndpoint
     *
     * @return string|null
     */
    public function getUserinfoEndpoint()
    {
        return $this->container['userinfoEndpoint'];
    }

    /**
     * Sets userinfoEndpoint
     *
     * @param string|null $userinfoEndpoint userinfoEndpoint
     *
     * @return self
     */
    public function setUserinfoEndpoint($userinfoEndpoint)
    {
        if (is_null($userinfoEndpoint)) {
            throw new \InvalidArgumentException('non-nullable userinfoEndpoint cannot be null');
        }
        $this->container['userinfoEndpoint'] = $userinfoEndpoint;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
        return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


