<?php

/**
 * PasskeyCredentialCreationResponseResponse
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  LoginRadius\Sdk\Internal\OpenApi
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * LoginRadius API
 *
 * This is a LoginRadius API server. Which you can use to authenticate and manage the user.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@loginradius.com
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.10.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace LoginRadius\Sdk\Internal\OpenApi\Model;

use \ArrayAccess;
use \LoginRadius\Sdk\Internal\OpenApi\ObjectSerializer;

/**
 * PasskeyCredentialCreationResponseResponse Class Doc Comment
 *
 * @category Class
 * @description The authenticator&#39;s response to the client&#39;s request to create a credential. Contains attestation information that can be used to verify the credential&#39;s origin.
 * @package  LoginRadius\Sdk\Internal\OpenApi
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class PasskeyCredentialCreationResponseResponse implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'PasskeyCredentialCreationResponse_response';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'clientDataJSON' => 'string',
        'attestationObject' => 'string',
        'transports' => 'string[]'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'clientDataJSON' => null,
        'attestationObject' => null,
        'transports' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'clientDataJSON' => false,
        'attestationObject' => false,
        'transports' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'clientDataJSON' => 'clientDataJSON',
        'attestationObject' => 'attestationObject',
        'transports' => 'transports'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'clientDataJSON' => 'setClientDataJSON',
        'attestationObject' => 'setAttestationObject',
        'transports' => 'setTransports'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'clientDataJSON' => 'getClientDataJSON',
        'attestationObject' => 'getAttestationObject',
        'transports' => 'getTransports'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }

    public const TRANSPORTS_USB = 'usb';
    public const TRANSPORTS_NFC = 'nfc';
    public const TRANSPORTS_BLE = 'ble';
    public const TRANSPORTS_INTERNAL = 'internal';
    public const TRANSPORTS_HYBRID = 'hybrid';

    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getTransportsAllowableValues()
    {
        return [
            self::TRANSPORTS_USB,
            self::TRANSPORTS_NFC,
            self::TRANSPORTS_BLE,
            self::TRANSPORTS_INTERNAL,
            self::TRANSPORTS_HYBRID,
        ];
    }

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->setIfExists('clientDataJSON', $data ?? [], null);
        $this->setIfExists('attestationObject', $data ?? [], null);
        $this->setIfExists('transports', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['clientDataJSON'] === null) {
            $invalidProperties[] = "'clientDataJSON' can't be null";
        }
        if ($this->container['attestationObject'] === null) {
            $invalidProperties[] = "'attestationObject' can't be null";
        }
        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets clientDataJSON
     *
     * @return string
     */
    public function getClientDataJSON()
    {
        return $this->container['clientDataJSON'];
    }

    /**
     * Sets clientDataJSON
     *
     * @param string $clientDataJSON Base64URL-encoded JSON serialized client data. Contains information about the credential creation like the challenge, origin, and type of credential.
     *
     * @return self
     */
    public function setClientDataJSON($clientDataJSON)
    {
        if (is_null($clientDataJSON)) {
            throw new \InvalidArgumentException('non-nullable clientDataJSON cannot be null');
        }
        $this->container['clientDataJSON'] = $clientDataJSON;

        return $this;
    }

    /**
     * Gets attestationObject
     *
     * @return string
     */
    public function getAttestationObject()
    {
        return $this->container['attestationObject'];
    }

    /**
     * Sets attestationObject
     *
     * @param string $attestationObject Base64URL-encoded attestation object. Contains the attestation statement and  authenticator data used to verify the credential's provenance.
     *
     * @return self
     */
    public function setAttestationObject($attestationObject)
    {
        if (is_null($attestationObject)) {
            throw new \InvalidArgumentException('non-nullable attestationObject cannot be null');
        }
        $this->container['attestationObject'] = $attestationObject;

        return $this;
    }

    /**
     * Gets transports
     *
     * @return string[]|null
     */
    public function getTransports()
    {
        return $this->container['transports'];
    }

    /**
     * Sets transports
     *
     * @param string[]|null $transports List of transports supported by the authenticator for this credential. May be included by the client or extracted from attestation metadata.
     *
     * @return self
     */
    public function setTransports($transports)
    {
        if (is_null($transports)) {
            throw new \InvalidArgumentException('non-nullable transports cannot be null');
        }
        $allowedValues = $this->getTransportsAllowableValues();
        if (array_diff($transports, $allowedValues)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value for 'transports', must be one of '%s'",
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['transports'] = $transports;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
        return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


