<?php

/**
 * TwoFactorAuthenticationTokenObject
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  LoginRadius\Sdk\Internal\OpenApi
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * LoginRadius API
 *
 * This is a LoginRadius API server. Which you can use to authenticate and manage the user.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@loginradius.com
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.10.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace LoginRadius\Sdk\Internal\OpenApi\Model;

use \ArrayAccess;
use \LoginRadius\Sdk\Internal\OpenApi\ObjectSerializer;

/**
 * TwoFactorAuthenticationTokenObject Class Doc Comment
 *
 * @category Class
 * @description This holds the second factor authentication settings including SecondFactorAuthentication token
 * @package  LoginRadius\Sdk\Internal\OpenApi
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class TwoFactorAuthenticationTokenObject implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'TwoFactorAuthenticationTokenObject';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'secondFactorAuthenticationToken' => 'string',
        'expireIn' => '\DateTime',
        'qRCode' => 'string',
        'pushQRCode' => 'string',
        'manualEntryCode' => 'string',
        'duoAuthEndpoint' => 'string',
        'isGoogleAuthenticatorVerified' => 'bool',
        'isPushDeviceRegistered' => 'bool',
        'isAuthenticatorVerified' => 'bool',
        'isEmailOtpAuthenticatorVerified' => 'bool',
        'isOTPAuthenticatorVerified' => 'bool',
        'isDuoAuthenticatorVerified' => 'bool',
        'isPasskeyAuthenticatorVerified' => 'bool',
        'oTPPhoneNo' => 'string',
        'oTPStatus' => '\LoginRadius\Sdk\Internal\OpenApi\Model\SMSResponseData',
        'email' => 'string[]',
        'emailOTPStatus' => '\LoginRadius\Sdk\Internal\OpenApi\Model\EmailOTPStatus',
        'isSecurityQuestionAuthenticatorVerified' => 'bool',
        'securityQuestions' => '\LoginRadius\Sdk\Internal\OpenApi\Model\SecurityQuestions[]'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'secondFactorAuthenticationToken' => null,
        'expireIn' => 'date-time',
        'qRCode' => null,
        'pushQRCode' => null,
        'manualEntryCode' => null,
        'duoAuthEndpoint' => null,
        'isGoogleAuthenticatorVerified' => null,
        'isPushDeviceRegistered' => null,
        'isAuthenticatorVerified' => null,
        'isEmailOtpAuthenticatorVerified' => null,
        'isOTPAuthenticatorVerified' => null,
        'isDuoAuthenticatorVerified' => null,
        'isPasskeyAuthenticatorVerified' => null,
        'oTPPhoneNo' => null,
        'oTPStatus' => null,
        'email' => 'email',
        'emailOTPStatus' => null,
        'isSecurityQuestionAuthenticatorVerified' => null,
        'securityQuestions' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'secondFactorAuthenticationToken' => false,
        'expireIn' => false,
        'qRCode' => true,
        'pushQRCode' => true,
        'manualEntryCode' => true,
        'duoAuthEndpoint' => true,
        'isGoogleAuthenticatorVerified' => false,
        'isPushDeviceRegistered' => false,
        'isAuthenticatorVerified' => false,
        'isEmailOtpAuthenticatorVerified' => false,
        'isOTPAuthenticatorVerified' => false,
        'isDuoAuthenticatorVerified' => false,
        'isPasskeyAuthenticatorVerified' => false,
        'oTPPhoneNo' => true,
        'oTPStatus' => false,
        'email' => false,
        'emailOTPStatus' => false,
        'isSecurityQuestionAuthenticatorVerified' => false,
        'securityQuestions' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'secondFactorAuthenticationToken' => 'SecondFactorAuthenticationToken',
        'expireIn' => 'ExpireIn',
        'qRCode' => 'QRCode',
        'pushQRCode' => 'PushQRCode',
        'manualEntryCode' => 'ManualEntryCode',
        'duoAuthEndpoint' => 'DuoAuthEndpoint',
        'isGoogleAuthenticatorVerified' => 'IsGoogleAuthenticatorVerified',
        'isPushDeviceRegistered' => 'IsPushDeviceRegistered',
        'isAuthenticatorVerified' => 'IsAuthenticatorVerified',
        'isEmailOtpAuthenticatorVerified' => 'IsEmailOtpAuthenticatorVerified',
        'isOTPAuthenticatorVerified' => 'IsOTPAuthenticatorVerified',
        'isDuoAuthenticatorVerified' => 'IsDuoAuthenticatorVerified',
        'isPasskeyAuthenticatorVerified' => 'IsPasskeyAuthenticatorVerified',
        'oTPPhoneNo' => 'OTPPhoneNo',
        'oTPStatus' => 'OTPStatus',
        'email' => 'Email',
        'emailOTPStatus' => 'EmailOTPStatus',
        'isSecurityQuestionAuthenticatorVerified' => 'IsSecurityQuestionAuthenticatorVerified',
        'securityQuestions' => 'SecurityQuestions'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'secondFactorAuthenticationToken' => 'setSecondFactorAuthenticationToken',
        'expireIn' => 'setExpireIn',
        'qRCode' => 'setQRCode',
        'pushQRCode' => 'setPushQRCode',
        'manualEntryCode' => 'setManualEntryCode',
        'duoAuthEndpoint' => 'setDuoAuthEndpoint',
        'isGoogleAuthenticatorVerified' => 'setIsGoogleAuthenticatorVerified',
        'isPushDeviceRegistered' => 'setIsPushDeviceRegistered',
        'isAuthenticatorVerified' => 'setIsAuthenticatorVerified',
        'isEmailOtpAuthenticatorVerified' => 'setIsEmailOtpAuthenticatorVerified',
        'isOTPAuthenticatorVerified' => 'setIsOTPAuthenticatorVerified',
        'isDuoAuthenticatorVerified' => 'setIsDuoAuthenticatorVerified',
        'isPasskeyAuthenticatorVerified' => 'setIsPasskeyAuthenticatorVerified',
        'oTPPhoneNo' => 'setOTPPhoneNo',
        'oTPStatus' => 'setOTPStatus',
        'email' => 'setEmail',
        'emailOTPStatus' => 'setEmailOTPStatus',
        'isSecurityQuestionAuthenticatorVerified' => 'setIsSecurityQuestionAuthenticatorVerified',
        'securityQuestions' => 'setSecurityQuestions'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'secondFactorAuthenticationToken' => 'getSecondFactorAuthenticationToken',
        'expireIn' => 'getExpireIn',
        'qRCode' => 'getQRCode',
        'pushQRCode' => 'getPushQRCode',
        'manualEntryCode' => 'getManualEntryCode',
        'duoAuthEndpoint' => 'getDuoAuthEndpoint',
        'isGoogleAuthenticatorVerified' => 'getIsGoogleAuthenticatorVerified',
        'isPushDeviceRegistered' => 'getIsPushDeviceRegistered',
        'isAuthenticatorVerified' => 'getIsAuthenticatorVerified',
        'isEmailOtpAuthenticatorVerified' => 'getIsEmailOtpAuthenticatorVerified',
        'isOTPAuthenticatorVerified' => 'getIsOTPAuthenticatorVerified',
        'isDuoAuthenticatorVerified' => 'getIsDuoAuthenticatorVerified',
        'isPasskeyAuthenticatorVerified' => 'getIsPasskeyAuthenticatorVerified',
        'oTPPhoneNo' => 'getOTPPhoneNo',
        'oTPStatus' => 'getOTPStatus',
        'email' => 'getEmail',
        'emailOTPStatus' => 'getEmailOTPStatus',
        'isSecurityQuestionAuthenticatorVerified' => 'getIsSecurityQuestionAuthenticatorVerified',
        'securityQuestions' => 'getSecurityQuestions'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->setIfExists('secondFactorAuthenticationToken', $data ?? [], null);
        $this->setIfExists('expireIn', $data ?? [], null);
        $this->setIfExists('qRCode', $data ?? [], null);
        $this->setIfExists('pushQRCode', $data ?? [], null);
        $this->setIfExists('manualEntryCode', $data ?? [], null);
        $this->setIfExists('duoAuthEndpoint', $data ?? [], null);
        $this->setIfExists('isGoogleAuthenticatorVerified', $data ?? [], null);
        $this->setIfExists('isPushDeviceRegistered', $data ?? [], null);
        $this->setIfExists('isAuthenticatorVerified', $data ?? [], null);
        $this->setIfExists('isEmailOtpAuthenticatorVerified', $data ?? [], null);
        $this->setIfExists('isOTPAuthenticatorVerified', $data ?? [], null);
        $this->setIfExists('isDuoAuthenticatorVerified', $data ?? [], null);
        $this->setIfExists('isPasskeyAuthenticatorVerified', $data ?? [], null);
        $this->setIfExists('oTPPhoneNo', $data ?? [], null);
        $this->setIfExists('oTPStatus', $data ?? [], null);
        $this->setIfExists('email', $data ?? [], null);
        $this->setIfExists('emailOTPStatus', $data ?? [], null);
        $this->setIfExists('isSecurityQuestionAuthenticatorVerified', $data ?? [], null);
        $this->setIfExists('securityQuestions', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets secondFactorAuthenticationToken
     *
     * @return string|null
     */
    public function getSecondFactorAuthenticationToken()
    {
        return $this->container['secondFactorAuthenticationToken'];
    }

    /**
     * Sets secondFactorAuthenticationToken
     *
     * @param string|null $secondFactorAuthenticationToken Token for second factor authentication
     *
     * @return self
     */
    public function setSecondFactorAuthenticationToken($secondFactorAuthenticationToken)
    {
        if (is_null($secondFactorAuthenticationToken)) {
            throw new \InvalidArgumentException('non-nullable secondFactorAuthenticationToken cannot be null');
        }
        $this->container['secondFactorAuthenticationToken'] = $secondFactorAuthenticationToken;

        return $this;
    }

    /**
     * Gets expireIn
     *
     * @return \DateTime|null
     */
    public function getExpireIn()
    {
        return $this->container['expireIn'];
    }

    /**
     * Sets expireIn
     *
     * @param \DateTime|null $expireIn Expiration time of the token
     *
     * @return self
     */
    public function setExpireIn($expireIn)
    {
        if (is_null($expireIn)) {
            throw new \InvalidArgumentException('non-nullable expireIn cannot be null');
        }
        $this->container['expireIn'] = $expireIn;

        return $this;
    }

    /**
     * Gets qRCode
     *
     * @return string|null
     */
    public function getQRCode()
    {
        return $this->container['qRCode'];
    }

    /**
     * Sets qRCode
     *
     * @param string|null $qRCode qRCode
     *
     * @return self
     */
    public function setQRCode($qRCode)
    {
        if (is_null($qRCode)) {
            array_push($this->openAPINullablesSetToNull, 'qRCode');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('qRCode', $nullablesSetToNull, true);
            if ($index !== false) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['qRCode'] = $qRCode;

        return $this;
    }

    /**
     * Gets pushQRCode
     *
     * @return string|null
     */
    public function getPushQRCode()
    {
        return $this->container['pushQRCode'];
    }

    /**
     * Sets pushQRCode
     *
     * @param string|null $pushQRCode pushQRCode
     *
     * @return self
     */
    public function setPushQRCode($pushQRCode)
    {
        if (is_null($pushQRCode)) {
            array_push($this->openAPINullablesSetToNull, 'pushQRCode');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('pushQRCode', $nullablesSetToNull, true);
            if ($index !== false) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['pushQRCode'] = $pushQRCode;

        return $this;
    }

    /**
     * Gets manualEntryCode
     *
     * @return string|null
     */
    public function getManualEntryCode()
    {
        return $this->container['manualEntryCode'];
    }

    /**
     * Sets manualEntryCode
     *
     * @param string|null $manualEntryCode manualEntryCode
     *
     * @return self
     */
    public function setManualEntryCode($manualEntryCode)
    {
        if (is_null($manualEntryCode)) {
            array_push($this->openAPINullablesSetToNull, 'manualEntryCode');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('manualEntryCode', $nullablesSetToNull, true);
            if ($index !== false) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['manualEntryCode'] = $manualEntryCode;

        return $this;
    }

    /**
     * Gets duoAuthEndpoint
     *
     * @return string|null
     */
    public function getDuoAuthEndpoint()
    {
        return $this->container['duoAuthEndpoint'];
    }

    /**
     * Sets duoAuthEndpoint
     *
     * @param string|null $duoAuthEndpoint duoAuthEndpoint
     *
     * @return self
     */
    public function setDuoAuthEndpoint($duoAuthEndpoint)
    {
        if (is_null($duoAuthEndpoint)) {
            array_push($this->openAPINullablesSetToNull, 'duoAuthEndpoint');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('duoAuthEndpoint', $nullablesSetToNull, true);
            if ($index !== false) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['duoAuthEndpoint'] = $duoAuthEndpoint;

        return $this;
    }

    /**
     * Gets isGoogleAuthenticatorVerified
     *
     * @return bool|null
     */
    public function getIsGoogleAuthenticatorVerified()
    {
        return $this->container['isGoogleAuthenticatorVerified'];
    }

    /**
     * Sets isGoogleAuthenticatorVerified
     *
     * @param bool|null $isGoogleAuthenticatorVerified isGoogleAuthenticatorVerified
     *
     * @return self
     */
    public function setIsGoogleAuthenticatorVerified($isGoogleAuthenticatorVerified)
    {
        if (is_null($isGoogleAuthenticatorVerified)) {
            throw new \InvalidArgumentException('non-nullable isGoogleAuthenticatorVerified cannot be null');
        }
        $this->container['isGoogleAuthenticatorVerified'] = $isGoogleAuthenticatorVerified;

        return $this;
    }

    /**
     * Gets isPushDeviceRegistered
     *
     * @return bool|null
     */
    public function getIsPushDeviceRegistered()
    {
        return $this->container['isPushDeviceRegistered'];
    }

    /**
     * Sets isPushDeviceRegistered
     *
     * @param bool|null $isPushDeviceRegistered isPushDeviceRegistered
     *
     * @return self
     */
    public function setIsPushDeviceRegistered($isPushDeviceRegistered)
    {
        if (is_null($isPushDeviceRegistered)) {
            throw new \InvalidArgumentException('non-nullable isPushDeviceRegistered cannot be null');
        }
        $this->container['isPushDeviceRegistered'] = $isPushDeviceRegistered;

        return $this;
    }

    /**
     * Gets isAuthenticatorVerified
     *
     * @return bool|null
     */
    public function getIsAuthenticatorVerified()
    {
        return $this->container['isAuthenticatorVerified'];
    }

    /**
     * Sets isAuthenticatorVerified
     *
     * @param bool|null $isAuthenticatorVerified isAuthenticatorVerified
     *
     * @return self
     */
    public function setIsAuthenticatorVerified($isAuthenticatorVerified)
    {
        if (is_null($isAuthenticatorVerified)) {
            throw new \InvalidArgumentException('non-nullable isAuthenticatorVerified cannot be null');
        }
        $this->container['isAuthenticatorVerified'] = $isAuthenticatorVerified;

        return $this;
    }

    /**
     * Gets isEmailOtpAuthenticatorVerified
     *
     * @return bool|null
     */
    public function getIsEmailOtpAuthenticatorVerified()
    {
        return $this->container['isEmailOtpAuthenticatorVerified'];
    }

    /**
     * Sets isEmailOtpAuthenticatorVerified
     *
     * @param bool|null $isEmailOtpAuthenticatorVerified isEmailOtpAuthenticatorVerified
     *
     * @return self
     */
    public function setIsEmailOtpAuthenticatorVerified($isEmailOtpAuthenticatorVerified)
    {
        if (is_null($isEmailOtpAuthenticatorVerified)) {
            throw new \InvalidArgumentException('non-nullable isEmailOtpAuthenticatorVerified cannot be null');
        }
        $this->container['isEmailOtpAuthenticatorVerified'] = $isEmailOtpAuthenticatorVerified;

        return $this;
    }

    /**
     * Gets isOTPAuthenticatorVerified
     *
     * @return bool|null
     */
    public function getIsOTPAuthenticatorVerified()
    {
        return $this->container['isOTPAuthenticatorVerified'];
    }

    /**
     * Sets isOTPAuthenticatorVerified
     *
     * @param bool|null $isOTPAuthenticatorVerified isOTPAuthenticatorVerified
     *
     * @return self
     */
    public function setIsOTPAuthenticatorVerified($isOTPAuthenticatorVerified)
    {
        if (is_null($isOTPAuthenticatorVerified)) {
            throw new \InvalidArgumentException('non-nullable isOTPAuthenticatorVerified cannot be null');
        }
        $this->container['isOTPAuthenticatorVerified'] = $isOTPAuthenticatorVerified;

        return $this;
    }

    /**
     * Gets isDuoAuthenticatorVerified
     *
     * @return bool|null
     */
    public function getIsDuoAuthenticatorVerified()
    {
        return $this->container['isDuoAuthenticatorVerified'];
    }

    /**
     * Sets isDuoAuthenticatorVerified
     *
     * @param bool|null $isDuoAuthenticatorVerified isDuoAuthenticatorVerified
     *
     * @return self
     */
    public function setIsDuoAuthenticatorVerified($isDuoAuthenticatorVerified)
    {
        if (is_null($isDuoAuthenticatorVerified)) {
            throw new \InvalidArgumentException('non-nullable isDuoAuthenticatorVerified cannot be null');
        }
        $this->container['isDuoAuthenticatorVerified'] = $isDuoAuthenticatorVerified;

        return $this;
    }

    /**
     * Gets isPasskeyAuthenticatorVerified
     *
     * @return bool|null
     */
    public function getIsPasskeyAuthenticatorVerified()
    {
        return $this->container['isPasskeyAuthenticatorVerified'];
    }

    /**
     * Sets isPasskeyAuthenticatorVerified
     *
     * @param bool|null $isPasskeyAuthenticatorVerified isPasskeyAuthenticatorVerified
     *
     * @return self
     */
    public function setIsPasskeyAuthenticatorVerified($isPasskeyAuthenticatorVerified)
    {
        if (is_null($isPasskeyAuthenticatorVerified)) {
            throw new \InvalidArgumentException('non-nullable isPasskeyAuthenticatorVerified cannot be null');
        }
        $this->container['isPasskeyAuthenticatorVerified'] = $isPasskeyAuthenticatorVerified;

        return $this;
    }

    /**
     * Gets oTPPhoneNo
     *
     * @return string|null
     */
    public function getOTPPhoneNo()
    {
        return $this->container['oTPPhoneNo'];
    }

    /**
     * Sets oTPPhoneNo
     *
     * @param string|null $oTPPhoneNo oTPPhoneNo
     *
     * @return self
     */
    public function setOTPPhoneNo($oTPPhoneNo)
    {
        if (is_null($oTPPhoneNo)) {
            array_push($this->openAPINullablesSetToNull, 'oTPPhoneNo');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('oTPPhoneNo', $nullablesSetToNull, true);
            if ($index !== false) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['oTPPhoneNo'] = $oTPPhoneNo;

        return $this;
    }

    /**
     * Gets oTPStatus
     *
     * @return \LoginRadius\Sdk\Internal\OpenApi\Model\SMSResponseData|null
     */
    public function getOTPStatus()
    {
        return $this->container['oTPStatus'];
    }

    /**
     * Sets oTPStatus
     *
     * @param \LoginRadius\Sdk\Internal\OpenApi\Model\SMSResponseData|null $oTPStatus oTPStatus
     *
     * @return self
     */
    public function setOTPStatus($oTPStatus)
    {
        if (is_null($oTPStatus)) {
            throw new \InvalidArgumentException('non-nullable oTPStatus cannot be null');
        }
        $this->container['oTPStatus'] = $oTPStatus;

        return $this;
    }

    /**
     * Gets email
     *
     * @return string[]|null
     */
    public function getEmail()
    {
        return $this->container['email'];
    }

    /**
     * Sets email
     *
     * @param string[]|null $email email
     *
     * @return self
     */
    public function setEmail($email)
    {
        if (is_null($email)) {
            throw new \InvalidArgumentException('non-nullable email cannot be null');
        }
        $this->container['email'] = $email;

        return $this;
    }

    /**
     * Gets emailOTPStatus
     *
     * @return \LoginRadius\Sdk\Internal\OpenApi\Model\EmailOTPStatus|null
     */
    public function getEmailOTPStatus()
    {
        return $this->container['emailOTPStatus'];
    }

    /**
     * Sets emailOTPStatus
     *
     * @param \LoginRadius\Sdk\Internal\OpenApi\Model\EmailOTPStatus|null $emailOTPStatus emailOTPStatus
     *
     * @return self
     */
    public function setEmailOTPStatus($emailOTPStatus)
    {
        if (is_null($emailOTPStatus)) {
            throw new \InvalidArgumentException('non-nullable emailOTPStatus cannot be null');
        }
        $this->container['emailOTPStatus'] = $emailOTPStatus;

        return $this;
    }

    /**
     * Gets isSecurityQuestionAuthenticatorVerified
     *
     * @return bool|null
     */
    public function getIsSecurityQuestionAuthenticatorVerified()
    {
        return $this->container['isSecurityQuestionAuthenticatorVerified'];
    }

    /**
     * Sets isSecurityQuestionAuthenticatorVerified
     *
     * @param bool|null $isSecurityQuestionAuthenticatorVerified isSecurityQuestionAuthenticatorVerified
     *
     * @return self
     */
    public function setIsSecurityQuestionAuthenticatorVerified($isSecurityQuestionAuthenticatorVerified)
    {
        if (is_null($isSecurityQuestionAuthenticatorVerified)) {
            throw new \InvalidArgumentException('non-nullable isSecurityQuestionAuthenticatorVerified cannot be null');
        }
        $this->container['isSecurityQuestionAuthenticatorVerified'] = $isSecurityQuestionAuthenticatorVerified;

        return $this;
    }

    /**
     * Gets securityQuestions
     *
     * @return \LoginRadius\Sdk\Internal\OpenApi\Model\SecurityQuestions[]|null
     */
    public function getSecurityQuestions()
    {
        return $this->container['securityQuestions'];
    }

    /**
     * Sets securityQuestions
     *
     * @param \LoginRadius\Sdk\Internal\OpenApi\Model\SecurityQuestions[]|null $securityQuestions securityQuestions
     *
     * @return self
     */
    public function setSecurityQuestions($securityQuestions)
    {
        if (is_null($securityQuestions)) {
            throw new \InvalidArgumentException('non-nullable securityQuestions cannot be null');
        }
        $this->container['securityQuestions'] = $securityQuestions;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
        return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


