<?php

// Code generated by the LoginRadius SDK generator; DO NOT EDIT.
//
// The service properties below are derived from the generated client in
// src/Internal/OpenApi, so a service added by a spec change appears here
// automatically. Base-URL precedence comes from the shared SDK manifest.

declare(strict_types=1);

namespace LoginRadius\Sdk;

use LoginRadius\Sdk\Internal\OpenApi\ApiException;
use LoginRadius\Sdk\Internal\OpenApi\Configuration;
use LoginRadius\Sdk\Internal\OpenApi\Api\AccountCustomObjectApi;
use LoginRadius\Sdk\Internal\OpenApi\Api\AccountSecurityApi;
use LoginRadius\Sdk\Internal\OpenApi\Api\AccountSessionApi;
use LoginRadius\Sdk\Internal\OpenApi\Api\AccountsApi;
use LoginRadius\Sdk\Internal\OpenApi\Api\BigCommerceSSOApi;
use LoginRadius\Sdk\Internal\OpenApi\Api\CaptchaConfigurationApi;
use LoginRadius\Sdk\Internal\OpenApi\Api\ConsentApi;
use LoginRadius\Sdk\Internal\OpenApi\Api\CrossDeviceSSOApi;
use LoginRadius\Sdk\Internal\OpenApi\Api\CustomFieldsApi;
use LoginRadius\Sdk\Internal\OpenApi\Api\CustomObjectApi;
use LoginRadius\Sdk\Internal\OpenApi\Api\CustomObjectsApi;
use LoginRadius\Sdk\Internal\OpenApi\Api\DomainAccessRestrictionsApi;
use LoginRadius\Sdk\Internal\OpenApi\Api\EmailTemplatesApi;
use LoginRadius\Sdk\Internal\OpenApi\Api\IPAccessRestrictionsApi;
use LoginRadius\Sdk\Internal\OpenApi\Api\IdentityApi;
use LoginRadius\Sdk\Internal\OpenApi\Api\InsightsApi;
use LoginRadius\Sdk\Internal\OpenApi\Api\JWTApi;
use LoginRadius\Sdk\Internal\OpenApi\Api\JWTCustomProvidersApi;
use LoginRadius\Sdk\Internal\OpenApi\Api\JWTIntegrationsApi;
use LoginRadius\Sdk\Internal\OpenApi\Api\LoginApi;
use LoginRadius\Sdk\Internal\OpenApi\Api\MultipurposeTokensApi;
use LoginRadius\Sdk\Internal\OpenApi\Api\OAuthApi;
use LoginRadius\Sdk\Internal\OpenApi\Api\OAuthClientsApi;
use LoginRadius\Sdk\Internal\OpenApi\Api\OAuthCustomProvidersApi;
use LoginRadius\Sdk\Internal\OpenApi\Api\OAuthIntegrationsApi;
use LoginRadius\Sdk\Internal\OpenApi\Api\OAuthM2MApi;
use LoginRadius\Sdk\Internal\OpenApi\Api\OIDCApi;
use LoginRadius\Sdk\Internal\OpenApi\Api\OrganizationApi;
use LoginRadius\Sdk\Internal\OpenApi\Api\OrganizationConnectionGroupRolesApi;
use LoginRadius\Sdk\Internal\OpenApi\Api\OrganizationConnectionsApi;
use LoginRadius\Sdk\Internal\OpenApi\Api\OrganizationDomainsApi;
use LoginRadius\Sdk\Internal\OpenApi\Api\OrganizationInvitationsApi;
use LoginRadius\Sdk\Internal\OpenApi\Api\OrganizationUserRolesApi;
use LoginRadius\Sdk\Internal\OpenApi\Api\PasskeyConfigurationApi;
use LoginRadius\Sdk\Internal\OpenApi\Api\PasswordApi;
use LoginRadius\Sdk\Internal\OpenApi\Api\PasswordPolicyApi;
use LoginRadius\Sdk\Internal\OpenApi\Api\PerfectMindSSOApi;
use LoginRadius\Sdk\Internal\OpenApi\Api\PermissionsApi;
use LoginRadius\Sdk\Internal\OpenApi\Api\PushNotificationConfigurationApi;
use LoginRadius\Sdk\Internal\OpenApi\Api\RegistrationApi;
use LoginRadius\Sdk\Internal\OpenApi\Api\RolesApi;
use LoginRadius\Sdk\Internal\OpenApi\Api\RolesManagementApi;
use LoginRadius\Sdk\Internal\OpenApi\Api\SAMLApi;
use LoginRadius\Sdk\Internal\OpenApi\Api\SAMLCustomProvidersApi;
use LoginRadius\Sdk\Internal\OpenApi\Api\SAMLIntegrationsApi;
use LoginRadius\Sdk\Internal\OpenApi\Api\SMSTemplatesApi;
use LoginRadius\Sdk\Internal\OpenApi\Api\SOTTApi;
use LoginRadius\Sdk\Internal\OpenApi\Api\SecondFactorConfigurationApi;
use LoginRadius\Sdk\Internal\OpenApi\Api\SecurityApi;
use LoginRadius\Sdk\Internal\OpenApi\Api\SecurityQuestionsApi;
use LoginRadius\Sdk\Internal\OpenApi\Api\SessionApi;
use LoginRadius\Sdk\Internal\OpenApi\Api\ShopifySSOApi;
use LoginRadius\Sdk\Internal\OpenApi\Api\SocialProvidersApi;
use LoginRadius\Sdk\Internal\OpenApi\Api\UserApi;
use LoginRadius\Sdk\Internal\OpenApi\Api\UserMigrationApi;
use LoginRadius\Sdk\Internal\OpenApi\Api\WebhooksApi;
use LoginRadius\Sdk\Internal\OpenApi\Api\WorkflowsApi;
use GuzzleHttp\Client as GuzzleClient;

/**
 * Entry point for all LoginRadius API calls.
 *
 * Construct once per tenant / credential set and reuse — every service
 * property shares the underlying HTTP client and configuration.
 *
 *     $client = new Client(new Config(apiKey: getenv('LR_API_KEY')));
 *
 * The client exposes 57 services, one per tag in the OpenAPI
 * specification. Customers must not reach into
 * `\LoginRadius\Sdk\Internal\OpenApi` — the supported surface is this namespace.
 */
final class Client
{
    private Config $config;
    private AuthenticatingClient $httpClient;

    // Service handles, one per OpenAPI tag (57 total). Names
    // drop the "Api" suffix for cleaner call sites.
    public readonly AccountCustomObjectApi $accountCustomObject;
    public readonly AccountSecurityApi $accountSecurity;
    public readonly AccountSessionApi $accountSession;
    public readonly AccountsApi $accounts;
    public readonly BigCommerceSSOApi $bigCommerceSSO;
    public readonly CaptchaConfigurationApi $captchaConfiguration;
    public readonly ConsentApi $consent;
    public readonly CrossDeviceSSOApi $crossDeviceSSO;
    public readonly CustomFieldsApi $customFields;
    public readonly CustomObjectApi $customObject;
    public readonly CustomObjectsApi $customObjects;
    public readonly DomainAccessRestrictionsApi $domainAccessRestrictions;
    public readonly EmailTemplatesApi $emailTemplates;
    public readonly IPAccessRestrictionsApi $ipAccessRestrictions;
    public readonly IdentityApi $identity;
    public readonly InsightsApi $insights;
    public readonly JWTApi $jwt;
    public readonly JWTCustomProvidersApi $jwtCustomProviders;
    public readonly JWTIntegrationsApi $jwtIntegrations;
    public readonly LoginApi $login;
    public readonly MultipurposeTokensApi $multipurposeTokens;
    public readonly OAuthApi $oauth;
    public readonly OAuthClientsApi $oauthClients;
    public readonly OAuthCustomProvidersApi $oauthCustomProviders;
    public readonly OAuthIntegrationsApi $oauthIntegrations;
    public readonly OAuthM2MApi $oauthM2M;
    public readonly OIDCApi $oidc;
    public readonly OrganizationApi $organization;
    public readonly OrganizationConnectionGroupRolesApi $organizationConnectionGroupRoles;
    public readonly OrganizationConnectionsApi $organizationConnections;
    public readonly OrganizationDomainsApi $organizationDomains;
    public readonly OrganizationInvitationsApi $organizationInvitations;
    public readonly OrganizationUserRolesApi $organizationUserRoles;
    public readonly PasskeyConfigurationApi $passkeyConfiguration;
    public readonly PasswordApi $password;
    public readonly PasswordPolicyApi $passwordPolicy;
    public readonly PerfectMindSSOApi $perfectMindSSO;
    public readonly PermissionsApi $permissions;
    public readonly PushNotificationConfigurationApi $pushNotificationConfiguration;
    public readonly RegistrationApi $registration;
    public readonly RolesApi $roles;
    public readonly RolesManagementApi $rolesManagement;
    public readonly SAMLApi $saml;
    public readonly SAMLCustomProvidersApi $samlCustomProviders;
    public readonly SAMLIntegrationsApi $samlIntegrations;
    public readonly SMSTemplatesApi $smsTemplates;
    public readonly SOTTApi $sott;
    public readonly SecondFactorConfigurationApi $secondFactorConfiguration;
    public readonly SecurityApi $security;
    public readonly SecurityQuestionsApi $securityQuestions;
    public readonly SessionApi $session;
    public readonly ShopifySSOApi $shopifySSO;
    public readonly SocialProvidersApi $socialProviders;
    public readonly UserApi $user;
    public readonly UserMigrationApi $userMigration;
    public readonly WebhooksApi $webhooks;
    public readonly WorkflowsApi $workflows;

    public function __construct(Config $config)
    {
        $this->config = $config;

        // A caller-supplied client is extended, never replaced: whatever
        // handler stack, proxy, or TLS options it carries keep applying — we
        // only ever wrap it so every request also gets credential injection.
        $inner = $config->httpClient() ?? new GuzzleClient(['timeout' => $config->timeoutSeconds()]);
        $this->httpClient = new AuthenticatingClient($inner, $config);

        $configuration = new Configuration();
        $configuration->setHost($config->resolveBaseUrl());
        self::applyServerSelection($configuration, $config);

        $this->accountCustomObject = new AccountCustomObjectApi($this->httpClient, $configuration);
        $this->accountSecurity = new AccountSecurityApi($this->httpClient, $configuration);
        $this->accountSession = new AccountSessionApi($this->httpClient, $configuration);
        $this->accounts = new AccountsApi($this->httpClient, $configuration);
        $this->bigCommerceSSO = new BigCommerceSSOApi($this->httpClient, $configuration);
        $this->captchaConfiguration = new CaptchaConfigurationApi($this->httpClient, $configuration);
        $this->consent = new ConsentApi($this->httpClient, $configuration);
        $this->crossDeviceSSO = new CrossDeviceSSOApi($this->httpClient, $configuration);
        $this->customFields = new CustomFieldsApi($this->httpClient, $configuration);
        $this->customObject = new CustomObjectApi($this->httpClient, $configuration);
        $this->customObjects = new CustomObjectsApi($this->httpClient, $configuration);
        $this->domainAccessRestrictions = new DomainAccessRestrictionsApi($this->httpClient, $configuration);
        $this->emailTemplates = new EmailTemplatesApi($this->httpClient, $configuration);
        $this->ipAccessRestrictions = new IPAccessRestrictionsApi($this->httpClient, $configuration);
        $this->identity = new IdentityApi($this->httpClient, $configuration);
        $this->insights = new InsightsApi($this->httpClient, $configuration);
        $this->jwt = new JWTApi($this->httpClient, $configuration);
        $this->jwtCustomProviders = new JWTCustomProvidersApi($this->httpClient, $configuration);
        $this->jwtIntegrations = new JWTIntegrationsApi($this->httpClient, $configuration);
        $this->login = new LoginApi($this->httpClient, $configuration);
        $this->multipurposeTokens = new MultipurposeTokensApi($this->httpClient, $configuration);
        $this->oauth = new OAuthApi($this->httpClient, $configuration);
        $this->oauthClients = new OAuthClientsApi($this->httpClient, $configuration);
        $this->oauthCustomProviders = new OAuthCustomProvidersApi($this->httpClient, $configuration);
        $this->oauthIntegrations = new OAuthIntegrationsApi($this->httpClient, $configuration);
        $this->oauthM2M = new OAuthM2MApi($this->httpClient, $configuration);
        $this->oidc = new OIDCApi($this->httpClient, $configuration);
        $this->organization = new OrganizationApi($this->httpClient, $configuration);
        $this->organizationConnectionGroupRoles = new OrganizationConnectionGroupRolesApi($this->httpClient, $configuration);
        $this->organizationConnections = new OrganizationConnectionsApi($this->httpClient, $configuration);
        $this->organizationDomains = new OrganizationDomainsApi($this->httpClient, $configuration);
        $this->organizationInvitations = new OrganizationInvitationsApi($this->httpClient, $configuration);
        $this->organizationUserRoles = new OrganizationUserRolesApi($this->httpClient, $configuration);
        $this->passkeyConfiguration = new PasskeyConfigurationApi($this->httpClient, $configuration);
        $this->password = new PasswordApi($this->httpClient, $configuration);
        $this->passwordPolicy = new PasswordPolicyApi($this->httpClient, $configuration);
        $this->perfectMindSSO = new PerfectMindSSOApi($this->httpClient, $configuration);
        $this->permissions = new PermissionsApi($this->httpClient, $configuration);
        $this->pushNotificationConfiguration = new PushNotificationConfigurationApi($this->httpClient, $configuration);
        $this->registration = new RegistrationApi($this->httpClient, $configuration);
        $this->roles = new RolesApi($this->httpClient, $configuration);
        $this->rolesManagement = new RolesManagementApi($this->httpClient, $configuration);
        $this->saml = new SAMLApi($this->httpClient, $configuration);
        $this->samlCustomProviders = new SAMLCustomProvidersApi($this->httpClient, $configuration);
        $this->samlIntegrations = new SAMLIntegrationsApi($this->httpClient, $configuration);
        $this->smsTemplates = new SMSTemplatesApi($this->httpClient, $configuration);
        $this->sott = new SOTTApi($this->httpClient, $configuration);
        $this->secondFactorConfiguration = new SecondFactorConfigurationApi($this->httpClient, $configuration);
        $this->security = new SecurityApi($this->httpClient, $configuration);
        $this->securityQuestions = new SecurityQuestionsApi($this->httpClient, $configuration);
        $this->session = new SessionApi($this->httpClient, $configuration);
        $this->shopifySSO = new ShopifySSOApi($this->httpClient, $configuration);
        $this->socialProviders = new SocialProvidersApi($this->httpClient, $configuration);
        $this->user = new UserApi($this->httpClient, $configuration);
        $this->userMigration = new UserMigrationApi($this->httpClient, $configuration);
        $this->webhooks = new WebhooksApi($this->httpClient, $configuration);
        $this->workflows = new WorkflowsApi($this->httpClient, $configuration);
    }

    /** The configuration this client was built from. */
    public function config(): Config
    {
        return $this->config;
    }

    /**
     * The underlying HTTP client. Exposed for tests that need to inspect the
     * transport; production code should configure via {@see Config}.
     */
    public function httpClient(): AuthenticatingClient
    {
        return $this->httpClient;
    }

    /**
     * Converts a generated {@see ApiException} into the facade's typed
     * exception, so callers branch on isAuth() / isRateLimit() rather than on
     * status codes.
     */
    public static function toLoginRadiusException(ApiException $e): LoginRadiusException
    {
        return LoginRadiusException::from($e);
    }

    /**
     * Reconciles the per-operation server lists the spec pins with the
     * client's configuration.
     *
     * The spec pins 42 operations to their own host —
     * cloud-api, migration, and the tenant-hub / custom-domain templates. The
     * generator keeps each pin as its own host-settings array on the
     * operation, resolved through Configuration::getHostString() with a
     * per-call `$variables` argument the generated method signature exposes —
     * so without wiring, a caller would have to pass `$variables` on every
     * single call to get their own tenant instead of the spec's "example"
     * placeholder. `Configuration::getLoginRadiusServerVariables()` (added by
     * the SDK generator) is what every pinned
     * operation call site now merges under its own `$variables`, so this only
     * has to be set once, here.
     */
    private static function applyServerSelection(Configuration $configuration, Config $cfg): void
    {
        $vars = [];
        $vars["TenantName"] = ($cfg->domain() !== null && $cfg->domain() !== '')
            ? $cfg->domain()
            : "TenantName";
        $vars["CustomDomain"] = ($cfg->customDomain() !== null && $cfg->customDomain() !== '')
            ? $cfg->customDomain()
            : "auth.example.com";
        $vars["domain"] = ($cfg->domain() !== null && $cfg->domain() !== '')
            ? $cfg->domain()
            : "example";
        $configuration->setLoginRadiusServerVariables($vars);

        // Escape hatch matching what the generated layer supports: selects
        // from the spec's own server list for the handful of pinned
        // operations that declare more than one host-settings entry. Most
        // operations are unpinned and read Configuration::getHost() instead,
        // which this does not affect.
        if ($cfg->serverIndex() !== null) {
            $configuration->setHostIndex($cfg->serverIndex());
        }

        // An explicit base URL means "send everything here" — a proxy, a
        // mock, or a staging environment. Without this, a caller who set one
        // would still see their migration, cloud-api, and OIDC traffic go to
        // production, because pinned operations never consult
        // Configuration::getHost(). `getLoginRadiusBaseUrlOverride` (added by
        // the SDK generator) is what every
        // pinned operation call site now checks BEFORE resolving its own
        // template — the only override the generated layer's per-operation
        // host settings expose.
        if ($cfg->baseURL() !== null && $cfg->baseURL() !== '') {
            $configuration->setLoginRadiusBaseUrlOverride($cfg->baseURL());
        }
    }
}
